import { sveltekit } from '@sveltejs/kit/vite';
import { SvelteKitPWA } from '@vite-pwa/sveltekit';
import { defineConfig } from 'vite';

export default defineConfig({
	define: {
		__APP_VERSION__: JSON.stringify(process.env.npm_package_version || '1.8.1')
	},
	build: {
		chunkSizeWarningLimit: 1000,
		// Enable minification and tree-shaking optimizations
		minify: 'esbuild',
		// Reduce build time by disabling source maps in production
		sourcemap: false,
		// Target modern browsers for smaller output
		target: 'es2020'
	},
	// Include WASM files as assets (needed for barcode-detector WASM polyfill)
	assetsInclude: ['**/*.wasm'],
	optimizeDeps: {
		// Exclude WASM modules from optimization to preserve dynamic imports
		exclude: ['barcode-detector']
	},
	plugins: [
		sveltekit(),
		SvelteKitPWA({
			// ========================================================================
			// INJECT MANIFEST STRATEGY - Custom Service Worker with Automatic Warmup
			// ========================================================================
			// Uses custom service-worker.ts with warmStrategyCache for automatic
			// API precaching on install (no user interaction needed)
			srcDir: 'src',
			filename: 'service-worker.ts',
			strategies: 'injectManifest',
			injectRegister: false, // Manual registration in +layout.svelte (better control)
			registerType: 'autoUpdate',

			devOptions: {
				enabled: true, // Enable SW for PWA testing (instant response + offline support)
				type: 'module'
			},
			manifest: {
				name: 'Savvy - Loyalty Cards Manager',
				short_name: 'Savvy',
				description:
					'Digitale Verwaltung von Kundenkarten, Gutscheinen und Geschenkkarten',
				theme_color: '#3b82f6',
				background_color: '#ffffff',
				display: 'standalone',
				start_url: '/',
				scope: '/',
				icons: [
					{
						src: '/icon-192.png',
						sizes: '192x192',
						type: 'image/png',
						purpose: 'any maskable'
					},
					{
						src: '/icon-512.png',
						sizes: '512x512',
						type: 'image/png',
						purpose: 'any maskable'
					}
				]
			},
			// ========================================================================
			// INJECT MANIFEST - Use SvelteKit output (not build/)
			// ========================================================================
			// IMPORTANT: globDirectory MUST point to .svelte-kit/output/client, NOT build/.
			// Reason: injectManifest runs BEFORE adapter-static copies files to build/.
			// If pointed at build/, the manifest gets stale hashes from a previous build,
			// causing "bad-precaching-response" 404 errors at runtime.
			//
			// index.html is NOT precached (generated by adapter after injectManifest).
			// Navigation is handled via NetworkFirst runtime caching in service-worker.ts.
			injectManifest: {
				globDirectory: '.svelte-kit/output/client',
				globPatterns: ['_app/**/*.{js,css,wasm}', '*.{png,svg,webmanifest}'],
				globIgnores: ['**/server/**', 'service-worker.*'],
				modifyURLPrefix: {},
				maximumFileSizeToCacheInBytes: 3 * 1024 * 1024 // 3MB
			}
		})
	],
	server: {
		port: 5173,
		proxy: {
			'/api': {
				target: 'http://api:8080', // Docker: api container on port 8080
				changeOrigin: true
			},
			'/auth': {
				target: 'http://api:8080', // OAuth routes
				changeOrigin: true
			},
			'/health': {
				target: 'http://api:8080', // Health check
				changeOrigin: true
			},
			'/ready': {
				target: 'http://api:8080', // Readiness check
				changeOrigin: true
			},
			'/metrics': {
				target: 'http://api:8080', // Prometheus metrics
				changeOrigin: true
			}
		}
	}
});
