// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGiftCardShareRepository is an autogenerated mock type for the GiftCardShareRepository type
type MockGiftCardShareRepository struct {
	mock.Mock
}

type MockGiftCardShareRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGiftCardShareRepository) EXPECT() *MockGiftCardShareRepository_Expecter {
	return &MockGiftCardShareRepository_Expecter{mock: &_m.Mock}
}

// CountByUser provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardShareRepository) CountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardShareRepository_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type MockGiftCardShareRepository_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardShareRepository_Expecter) CountByUser(ctx interface{}, userID interface{}) *MockGiftCardShareRepository_CountByUser_Call {
	return &MockGiftCardShareRepository_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID)}
}

func (_c *MockGiftCardShareRepository_CountByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardShareRepository_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_CountByUser_Call) Return(_a0 int64, _a1 error) *MockGiftCardShareRepository_CountByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardShareRepository_CountByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockGiftCardShareRepository_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, share
func (_m *MockGiftCardShareRepository) Create(ctx context.Context, share *models.GiftCardShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCardShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardShareRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGiftCardShareRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - share *models.GiftCardShare
func (_e *MockGiftCardShareRepository_Expecter) Create(ctx interface{}, share interface{}) *MockGiftCardShareRepository_Create_Call {
	return &MockGiftCardShareRepository_Create_Call{Call: _e.mock.On("Create", ctx, share)}
}

func (_c *MockGiftCardShareRepository_Create_Call) Run(run func(ctx context.Context, share *models.GiftCardShare)) *MockGiftCardShareRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCardShare))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_Create_Call) Return(_a0 error) *MockGiftCardShareRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardShareRepository_Create_Call) RunAndReturn(run func(context.Context, *models.GiftCardShare) error) *MockGiftCardShareRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByGiftCardAndUser provides a mock function with given fields: ctx, giftCardID, userID
func (_m *MockGiftCardShareRepository) DeleteByGiftCardAndUser(ctx context.Context, giftCardID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, giftCardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByGiftCardAndUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, giftCardID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByGiftCardAndUser'
type MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call struct {
	*mock.Call
}

// DeleteByGiftCardAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCardID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGiftCardShareRepository_Expecter) DeleteByGiftCardAndUser(ctx interface{}, giftCardID interface{}, userID interface{}) *MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call {
	return &MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call{Call: _e.mock.On("DeleteByGiftCardAndUser", ctx, giftCardID, userID)}
}

func (_c *MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call) Run(run func(ctx context.Context, giftCardID uuid.UUID, userID uuid.UUID)) *MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call) Return(_a0 error) *MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockGiftCardShareRepository_DeleteByGiftCardAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByGiftCardID provides a mock function with given fields: ctx, giftCardID
func (_m *MockGiftCardShareRepository) DeleteByGiftCardID(ctx context.Context, giftCardID uuid.UUID) error {
	ret := _m.Called(ctx, giftCardID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByGiftCardID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, giftCardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardShareRepository_DeleteByGiftCardID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByGiftCardID'
type MockGiftCardShareRepository_DeleteByGiftCardID_Call struct {
	*mock.Call
}

// DeleteByGiftCardID is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCardID uuid.UUID
func (_e *MockGiftCardShareRepository_Expecter) DeleteByGiftCardID(ctx interface{}, giftCardID interface{}) *MockGiftCardShareRepository_DeleteByGiftCardID_Call {
	return &MockGiftCardShareRepository_DeleteByGiftCardID_Call{Call: _e.mock.On("DeleteByGiftCardID", ctx, giftCardID)}
}

func (_c *MockGiftCardShareRepository_DeleteByGiftCardID_Call) Run(run func(ctx context.Context, giftCardID uuid.UUID)) *MockGiftCardShareRepository_DeleteByGiftCardID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_DeleteByGiftCardID_Call) Return(_a0 error) *MockGiftCardShareRepository_DeleteByGiftCardID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardShareRepository_DeleteByGiftCardID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGiftCardShareRepository_DeleteByGiftCardID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGiftCardAndUser provides a mock function with given fields: ctx, giftCardID, userID
func (_m *MockGiftCardShareRepository) GetByGiftCardAndUser(ctx context.Context, giftCardID uuid.UUID, userID uuid.UUID) (*models.GiftCardShare, error) {
	ret := _m.Called(ctx, giftCardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGiftCardAndUser")
	}

	var r0 *models.GiftCardShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.GiftCardShare, error)); ok {
		return rf(ctx, giftCardID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.GiftCardShare); ok {
		r0 = rf(ctx, giftCardID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GiftCardShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, giftCardID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardShareRepository_GetByGiftCardAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGiftCardAndUser'
type MockGiftCardShareRepository_GetByGiftCardAndUser_Call struct {
	*mock.Call
}

// GetByGiftCardAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCardID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGiftCardShareRepository_Expecter) GetByGiftCardAndUser(ctx interface{}, giftCardID interface{}, userID interface{}) *MockGiftCardShareRepository_GetByGiftCardAndUser_Call {
	return &MockGiftCardShareRepository_GetByGiftCardAndUser_Call{Call: _e.mock.On("GetByGiftCardAndUser", ctx, giftCardID, userID)}
}

func (_c *MockGiftCardShareRepository_GetByGiftCardAndUser_Call) Run(run func(ctx context.Context, giftCardID uuid.UUID, userID uuid.UUID)) *MockGiftCardShareRepository_GetByGiftCardAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_GetByGiftCardAndUser_Call) Return(_a0 *models.GiftCardShare, _a1 error) *MockGiftCardShareRepository_GetByGiftCardAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardShareRepository_GetByGiftCardAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.GiftCardShare, error)) *MockGiftCardShareRepository_GetByGiftCardAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGiftCardID provides a mock function with given fields: ctx, giftCardID
func (_m *MockGiftCardShareRepository) GetByGiftCardID(ctx context.Context, giftCardID uuid.UUID) ([]models.GiftCardShare, error) {
	ret := _m.Called(ctx, giftCardID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGiftCardID")
	}

	var r0 []models.GiftCardShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.GiftCardShare, error)); ok {
		return rf(ctx, giftCardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.GiftCardShare); ok {
		r0 = rf(ctx, giftCardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GiftCardShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, giftCardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardShareRepository_GetByGiftCardID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGiftCardID'
type MockGiftCardShareRepository_GetByGiftCardID_Call struct {
	*mock.Call
}

// GetByGiftCardID is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCardID uuid.UUID
func (_e *MockGiftCardShareRepository_Expecter) GetByGiftCardID(ctx interface{}, giftCardID interface{}) *MockGiftCardShareRepository_GetByGiftCardID_Call {
	return &MockGiftCardShareRepository_GetByGiftCardID_Call{Call: _e.mock.On("GetByGiftCardID", ctx, giftCardID)}
}

func (_c *MockGiftCardShareRepository_GetByGiftCardID_Call) Run(run func(ctx context.Context, giftCardID uuid.UUID)) *MockGiftCardShareRepository_GetByGiftCardID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_GetByGiftCardID_Call) Return(_a0 []models.GiftCardShare, _a1 error) *MockGiftCardShareRepository_GetByGiftCardID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardShareRepository_GetByGiftCardID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.GiftCardShare, error)) *MockGiftCardShareRepository_GetByGiftCardID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharedUserIDs provides a mock function with given fields: ctx, ownerID
func (_m *MockGiftCardShareRepository) GetSharedUserIDs(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSharedUserIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardShareRepository_GetSharedUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedUserIDs'
type MockGiftCardShareRepository_GetSharedUserIDs_Call struct {
	*mock.Call
}

// GetSharedUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *MockGiftCardShareRepository_Expecter) GetSharedUserIDs(ctx interface{}, ownerID interface{}) *MockGiftCardShareRepository_GetSharedUserIDs_Call {
	return &MockGiftCardShareRepository_GetSharedUserIDs_Call{Call: _e.mock.On("GetSharedUserIDs", ctx, ownerID)}
}

func (_c *MockGiftCardShareRepository_GetSharedUserIDs_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *MockGiftCardShareRepository_GetSharedUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_GetSharedUserIDs_Call) Return(_a0 []uuid.UUID, _a1 error) *MockGiftCardShareRepository_GetSharedUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardShareRepository_GetSharedUserIDs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *MockGiftCardShareRepository_GetSharedUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, share
func (_m *MockGiftCardShareRepository) Update(ctx context.Context, share *models.GiftCardShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCardShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardShareRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGiftCardShareRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - share *models.GiftCardShare
func (_e *MockGiftCardShareRepository_Expecter) Update(ctx interface{}, share interface{}) *MockGiftCardShareRepository_Update_Call {
	return &MockGiftCardShareRepository_Update_Call{Call: _e.mock.On("Update", ctx, share)}
}

func (_c *MockGiftCardShareRepository_Update_Call) Run(run func(ctx context.Context, share *models.GiftCardShare)) *MockGiftCardShareRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCardShare))
	})
	return _c
}

func (_c *MockGiftCardShareRepository_Update_Call) Return(_a0 error) *MockGiftCardShareRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardShareRepository_Update_Call) RunAndReturn(run func(context.Context, *models.GiftCardShare) error) *MockGiftCardShareRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGiftCardShareRepository creates a new instance of MockGiftCardShareRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGiftCardShareRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGiftCardShareRepository {
	mock := &MockGiftCardShareRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
