// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"
	"savvy/internal/repository"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCardServiceInterface is an autogenerated mock type for the CardServiceInterface type
type MockCardServiceInterface struct {
	mock.Mock
}

type MockCardServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCardServiceInterface) EXPECT() *MockCardServiceInterface_Expecter {
	return &MockCardServiceInterface_Expecter{mock: &_m.Mock}
}

// CanUserAccessCard provides a mock function with given fields: ctx, cardID, userID
func (_m *MockCardServiceInterface) CanUserAccessCard(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, cardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanUserAccessCard")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, cardID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, cardID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, cardID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardServiceInterface_CanUserAccessCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanUserAccessCard'
type MockCardServiceInterface_CanUserAccessCard_Call struct {
	*mock.Call
}

// CanUserAccessCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - userID uuid.UUID
func (_e *MockCardServiceInterface_Expecter) CanUserAccessCard(ctx interface{}, cardID interface{}, userID interface{}) *MockCardServiceInterface_CanUserAccessCard_Call {
	return &MockCardServiceInterface_CanUserAccessCard_Call{Call: _e.mock.On("CanUserAccessCard", ctx, cardID, userID)}
}

func (_c *MockCardServiceInterface_CanUserAccessCard_Call) Run(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID)) *MockCardServiceInterface_CanUserAccessCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardServiceInterface_CanUserAccessCard_Call) Return(_a0 bool, _a1 error) *MockCardServiceInterface_CanUserAccessCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardServiceInterface_CanUserAccessCard_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockCardServiceInterface_CanUserAccessCard_Call {
	_c.Call.Return(run)
	return _c
}

// CountUserCards provides a mock function with given fields: ctx, userID
func (_m *MockCardServiceInterface) CountUserCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserCards")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardServiceInterface_CountUserCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserCards'
type MockCardServiceInterface_CountUserCards_Call struct {
	*mock.Call
}

// CountUserCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCardServiceInterface_Expecter) CountUserCards(ctx interface{}, userID interface{}) *MockCardServiceInterface_CountUserCards_Call {
	return &MockCardServiceInterface_CountUserCards_Call{Call: _e.mock.On("CountUserCards", ctx, userID)}
}

func (_c *MockCardServiceInterface_CountUserCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCardServiceInterface_CountUserCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardServiceInterface_CountUserCards_Call) Return(_a0 int64, _a1 error) *MockCardServiceInterface_CountUserCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardServiceInterface_CountUserCards_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockCardServiceInterface_CountUserCards_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCard provides a mock function with given fields: ctx, card
func (_m *MockCardServiceInterface) CreateCard(ctx context.Context, card *models.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for CreateCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardServiceInterface_CreateCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCard'
type MockCardServiceInterface_CreateCard_Call struct {
	*mock.Call
}

// CreateCard is a helper method to define mock.On call
//   - ctx context.Context
//   - card *models.Card
func (_e *MockCardServiceInterface_Expecter) CreateCard(ctx interface{}, card interface{}) *MockCardServiceInterface_CreateCard_Call {
	return &MockCardServiceInterface_CreateCard_Call{Call: _e.mock.On("CreateCard", ctx, card)}
}

func (_c *MockCardServiceInterface_CreateCard_Call) Run(run func(ctx context.Context, card *models.Card)) *MockCardServiceInterface_CreateCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Card))
	})
	return _c
}

func (_c *MockCardServiceInterface_CreateCard_Call) Return(_a0 error) *MockCardServiceInterface_CreateCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardServiceInterface_CreateCard_Call) RunAndReturn(run func(context.Context, *models.Card) error) *MockCardServiceInterface_CreateCard_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCard provides a mock function with given fields: ctx, id
func (_m *MockCardServiceInterface) DeleteCard(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardServiceInterface_DeleteCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCard'
type MockCardServiceInterface_DeleteCard_Call struct {
	*mock.Call
}

// DeleteCard is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCardServiceInterface_Expecter) DeleteCard(ctx interface{}, id interface{}) *MockCardServiceInterface_DeleteCard_Call {
	return &MockCardServiceInterface_DeleteCard_Call{Call: _e.mock.On("DeleteCard", ctx, id)}
}

func (_c *MockCardServiceInterface_DeleteCard_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCardServiceInterface_DeleteCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardServiceInterface_DeleteCard_Call) Return(_a0 error) *MockCardServiceInterface_DeleteCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardServiceInterface_DeleteCard_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCardServiceInterface_DeleteCard_Call {
	_c.Call.Return(run)
	return _c
}

// GetCard provides a mock function with given fields: ctx, id
func (_m *MockCardServiceInterface) GetCard(ctx context.Context, id uuid.UUID) (*models.Card, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCard")
	}

	var r0 *models.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Card, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Card); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardServiceInterface_GetCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCard'
type MockCardServiceInterface_GetCard_Call struct {
	*mock.Call
}

// GetCard is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCardServiceInterface_Expecter) GetCard(ctx interface{}, id interface{}) *MockCardServiceInterface_GetCard_Call {
	return &MockCardServiceInterface_GetCard_Call{Call: _e.mock.On("GetCard", ctx, id)}
}

func (_c *MockCardServiceInterface_GetCard_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCardServiceInterface_GetCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardServiceInterface_GetCard_Call) Return(_a0 *models.Card, _a1 error) *MockCardServiceInterface_GetCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardServiceInterface_GetCard_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Card, error)) *MockCardServiceInterface_GetCard_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCardsPaginated provides a mock function with given fields: ctx, userID, page, perPage
func (_m *MockCardServiceInterface) GetUserCardsPaginated(ctx context.Context, userID uuid.UUID, page int, perPage int) (*repository.PaginatedResult[models.Card], error) {
	ret := _m.Called(ctx, userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCardsPaginated")
	}

	var r0 *repository.PaginatedResult[models.Card]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) (*repository.PaginatedResult[models.Card], error)); ok {
		return rf(ctx, userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) *repository.PaginatedResult[models.Card]); ok {
		r0 = rf(ctx, userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PaginatedResult[models.Card])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserCards provides a mock function with given fields: ctx, userID
func (_m *MockCardServiceInterface) GetUserCards(ctx context.Context, userID uuid.UUID) ([]models.Card, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCards")
	}

	var r0 []models.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Card, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Card); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardServiceInterface_GetUserCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCards'
type MockCardServiceInterface_GetUserCards_Call struct {
	*mock.Call
}

// GetUserCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCardServiceInterface_Expecter) GetUserCards(ctx interface{}, userID interface{}) *MockCardServiceInterface_GetUserCards_Call {
	return &MockCardServiceInterface_GetUserCards_Call{Call: _e.mock.On("GetUserCards", ctx, userID)}
}

func (_c *MockCardServiceInterface_GetUserCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCardServiceInterface_GetUserCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardServiceInterface_GetUserCards_Call) Return(_a0 []models.Card, _a1 error) *MockCardServiceInterface_GetUserCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardServiceInterface_GetUserCards_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Card, error)) *MockCardServiceInterface_GetUserCards_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCard provides a mock function with given fields: ctx, card
func (_m *MockCardServiceInterface) UpdateCard(ctx context.Context, card *models.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardServiceInterface_UpdateCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCard'
type MockCardServiceInterface_UpdateCard_Call struct {
	*mock.Call
}

// UpdateCard is a helper method to define mock.On call
//   - ctx context.Context
//   - card *models.Card
func (_e *MockCardServiceInterface_Expecter) UpdateCard(ctx interface{}, card interface{}) *MockCardServiceInterface_UpdateCard_Call {
	return &MockCardServiceInterface_UpdateCard_Call{Call: _e.mock.On("UpdateCard", ctx, card)}
}

func (_c *MockCardServiceInterface_UpdateCard_Call) Run(run func(ctx context.Context, card *models.Card)) *MockCardServiceInterface_UpdateCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Card))
	})
	return _c
}

func (_c *MockCardServiceInterface_UpdateCard_Call) Return(_a0 error) *MockCardServiceInterface_UpdateCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardServiceInterface_UpdateCard_Call) RunAndReturn(run func(context.Context, *models.Card) error) *MockCardServiceInterface_UpdateCard_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCardServiceInterface creates a new instance of MockCardServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCardServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCardServiceInterface {
	mock := &MockCardServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CheckDuplicate provides a mock function with given fields: ctx, cardNumber, userID, excludeID
func (m *MockCardServiceInterface) CheckDuplicate(ctx context.Context, cardNumber string, userID uuid.UUID, excludeID *uuid.UUID) (*models.Card, error) {
	ret := m.Called(ctx, cardNumber, userID, excludeID)
	var r0 *models.Card
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, *uuid.UUID) *models.Card); ok {
		r0 = rf(ctx, cardNumber, userID, excludeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Card)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(ctx, cardNumber, userID, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FindDeletedDuplicate provides a mock function with given fields: ctx, cardNumber, userID
func (m *MockCardServiceInterface) FindDeletedDuplicate(ctx context.Context, cardNumber string, userID uuid.UUID) (*models.Card, error) {
	ret := m.Called(ctx, cardNumber, userID)
	var r0 *models.Card
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *models.Card); ok {
		r0 = rf(ctx, cardNumber, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Card)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, cardNumber, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RestoreCard provides a mock function with given fields: ctx, id, userID
func (m *MockCardServiceInterface) RestoreCard(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*models.Card, error) {
	ret := m.Called(ctx, id, userID)
	var r0 *models.Card
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Card); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Card)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
