// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVoucherShareRepository is an autogenerated mock type for the VoucherShareRepository type
type MockVoucherShareRepository struct {
	mock.Mock
}

type MockVoucherShareRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoucherShareRepository) EXPECT() *MockVoucherShareRepository_Expecter {
	return &MockVoucherShareRepository_Expecter{mock: &_m.Mock}
}

// CountByUser provides a mock function with given fields: ctx, userID
func (_m *MockVoucherShareRepository) CountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoucherShareRepository_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type MockVoucherShareRepository_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockVoucherShareRepository_Expecter) CountByUser(ctx interface{}, userID interface{}) *MockVoucherShareRepository_CountByUser_Call {
	return &MockVoucherShareRepository_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID)}
}

func (_c *MockVoucherShareRepository_CountByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockVoucherShareRepository_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherShareRepository_CountByUser_Call) Return(_a0 int64, _a1 error) *MockVoucherShareRepository_CountByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoucherShareRepository_CountByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockVoucherShareRepository_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, share
func (_m *MockVoucherShareRepository) Create(ctx context.Context, share *models.VoucherShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.VoucherShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoucherShareRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVoucherShareRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - share *models.VoucherShare
func (_e *MockVoucherShareRepository_Expecter) Create(ctx interface{}, share interface{}) *MockVoucherShareRepository_Create_Call {
	return &MockVoucherShareRepository_Create_Call{Call: _e.mock.On("Create", ctx, share)}
}

func (_c *MockVoucherShareRepository_Create_Call) Run(run func(ctx context.Context, share *models.VoucherShare)) *MockVoucherShareRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.VoucherShare))
	})
	return _c
}

func (_c *MockVoucherShareRepository_Create_Call) Return(_a0 error) *MockVoucherShareRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoucherShareRepository_Create_Call) RunAndReturn(run func(context.Context, *models.VoucherShare) error) *MockVoucherShareRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByVoucherAndUser provides a mock function with given fields: ctx, voucherID, userID
func (_m *MockVoucherShareRepository) DeleteByVoucherAndUser(ctx context.Context, voucherID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, voucherID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByVoucherAndUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, voucherID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoucherShareRepository_DeleteByVoucherAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByVoucherAndUser'
type MockVoucherShareRepository_DeleteByVoucherAndUser_Call struct {
	*mock.Call
}

// DeleteByVoucherAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - voucherID uuid.UUID
//   - userID uuid.UUID
func (_e *MockVoucherShareRepository_Expecter) DeleteByVoucherAndUser(ctx interface{}, voucherID interface{}, userID interface{}) *MockVoucherShareRepository_DeleteByVoucherAndUser_Call {
	return &MockVoucherShareRepository_DeleteByVoucherAndUser_Call{Call: _e.mock.On("DeleteByVoucherAndUser", ctx, voucherID, userID)}
}

func (_c *MockVoucherShareRepository_DeleteByVoucherAndUser_Call) Run(run func(ctx context.Context, voucherID uuid.UUID, userID uuid.UUID)) *MockVoucherShareRepository_DeleteByVoucherAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherShareRepository_DeleteByVoucherAndUser_Call) Return(_a0 error) *MockVoucherShareRepository_DeleteByVoucherAndUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoucherShareRepository_DeleteByVoucherAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockVoucherShareRepository_DeleteByVoucherAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByVoucherID provides a mock function with given fields: ctx, voucherID
func (_m *MockVoucherShareRepository) DeleteByVoucherID(ctx context.Context, voucherID uuid.UUID) error {
	ret := _m.Called(ctx, voucherID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByVoucherID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, voucherID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoucherShareRepository_DeleteByVoucherID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByVoucherID'
type MockVoucherShareRepository_DeleteByVoucherID_Call struct {
	*mock.Call
}

// DeleteByVoucherID is a helper method to define mock.On call
//   - ctx context.Context
//   - voucherID uuid.UUID
func (_e *MockVoucherShareRepository_Expecter) DeleteByVoucherID(ctx interface{}, voucherID interface{}) *MockVoucherShareRepository_DeleteByVoucherID_Call {
	return &MockVoucherShareRepository_DeleteByVoucherID_Call{Call: _e.mock.On("DeleteByVoucherID", ctx, voucherID)}
}

func (_c *MockVoucherShareRepository_DeleteByVoucherID_Call) Run(run func(ctx context.Context, voucherID uuid.UUID)) *MockVoucherShareRepository_DeleteByVoucherID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherShareRepository_DeleteByVoucherID_Call) Return(_a0 error) *MockVoucherShareRepository_DeleteByVoucherID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoucherShareRepository_DeleteByVoucherID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockVoucherShareRepository_DeleteByVoucherID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByVoucherAndUser provides a mock function with given fields: ctx, voucherID, userID
func (_m *MockVoucherShareRepository) GetByVoucherAndUser(ctx context.Context, voucherID uuid.UUID, userID uuid.UUID) (*models.VoucherShare, error) {
	ret := _m.Called(ctx, voucherID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByVoucherAndUser")
	}

	var r0 *models.VoucherShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.VoucherShare, error)); ok {
		return rf(ctx, voucherID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.VoucherShare); ok {
		r0 = rf(ctx, voucherID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VoucherShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, voucherID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoucherShareRepository_GetByVoucherAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByVoucherAndUser'
type MockVoucherShareRepository_GetByVoucherAndUser_Call struct {
	*mock.Call
}

// GetByVoucherAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - voucherID uuid.UUID
//   - userID uuid.UUID
func (_e *MockVoucherShareRepository_Expecter) GetByVoucherAndUser(ctx interface{}, voucherID interface{}, userID interface{}) *MockVoucherShareRepository_GetByVoucherAndUser_Call {
	return &MockVoucherShareRepository_GetByVoucherAndUser_Call{Call: _e.mock.On("GetByVoucherAndUser", ctx, voucherID, userID)}
}

func (_c *MockVoucherShareRepository_GetByVoucherAndUser_Call) Run(run func(ctx context.Context, voucherID uuid.UUID, userID uuid.UUID)) *MockVoucherShareRepository_GetByVoucherAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherShareRepository_GetByVoucherAndUser_Call) Return(_a0 *models.VoucherShare, _a1 error) *MockVoucherShareRepository_GetByVoucherAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoucherShareRepository_GetByVoucherAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.VoucherShare, error)) *MockVoucherShareRepository_GetByVoucherAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByVoucherID provides a mock function with given fields: ctx, voucherID
func (_m *MockVoucherShareRepository) GetByVoucherID(ctx context.Context, voucherID uuid.UUID) ([]models.VoucherShare, error) {
	ret := _m.Called(ctx, voucherID)

	if len(ret) == 0 {
		panic("no return value specified for GetByVoucherID")
	}

	var r0 []models.VoucherShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.VoucherShare, error)); ok {
		return rf(ctx, voucherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.VoucherShare); ok {
		r0 = rf(ctx, voucherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.VoucherShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, voucherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoucherShareRepository_GetByVoucherID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByVoucherID'
type MockVoucherShareRepository_GetByVoucherID_Call struct {
	*mock.Call
}

// GetByVoucherID is a helper method to define mock.On call
//   - ctx context.Context
//   - voucherID uuid.UUID
func (_e *MockVoucherShareRepository_Expecter) GetByVoucherID(ctx interface{}, voucherID interface{}) *MockVoucherShareRepository_GetByVoucherID_Call {
	return &MockVoucherShareRepository_GetByVoucherID_Call{Call: _e.mock.On("GetByVoucherID", ctx, voucherID)}
}

func (_c *MockVoucherShareRepository_GetByVoucherID_Call) Run(run func(ctx context.Context, voucherID uuid.UUID)) *MockVoucherShareRepository_GetByVoucherID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherShareRepository_GetByVoucherID_Call) Return(_a0 []models.VoucherShare, _a1 error) *MockVoucherShareRepository_GetByVoucherID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoucherShareRepository_GetByVoucherID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.VoucherShare, error)) *MockVoucherShareRepository_GetByVoucherID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharedUserIDs provides a mock function with given fields: ctx, ownerID
func (_m *MockVoucherShareRepository) GetSharedUserIDs(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSharedUserIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoucherShareRepository_GetSharedUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedUserIDs'
type MockVoucherShareRepository_GetSharedUserIDs_Call struct {
	*mock.Call
}

// GetSharedUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *MockVoucherShareRepository_Expecter) GetSharedUserIDs(ctx interface{}, ownerID interface{}) *MockVoucherShareRepository_GetSharedUserIDs_Call {
	return &MockVoucherShareRepository_GetSharedUserIDs_Call{Call: _e.mock.On("GetSharedUserIDs", ctx, ownerID)}
}

func (_c *MockVoucherShareRepository_GetSharedUserIDs_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *MockVoucherShareRepository_GetSharedUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherShareRepository_GetSharedUserIDs_Call) Return(_a0 []uuid.UUID, _a1 error) *MockVoucherShareRepository_GetSharedUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoucherShareRepository_GetSharedUserIDs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *MockVoucherShareRepository_GetSharedUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, share
func (_m *MockVoucherShareRepository) Update(ctx context.Context, share *models.VoucherShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.VoucherShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoucherShareRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVoucherShareRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - share *models.VoucherShare
func (_e *MockVoucherShareRepository_Expecter) Update(ctx interface{}, share interface{}) *MockVoucherShareRepository_Update_Call {
	return &MockVoucherShareRepository_Update_Call{Call: _e.mock.On("Update", ctx, share)}
}

func (_c *MockVoucherShareRepository_Update_Call) Run(run func(ctx context.Context, share *models.VoucherShare)) *MockVoucherShareRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.VoucherShare))
	})
	return _c
}

func (_c *MockVoucherShareRepository_Update_Call) Return(_a0 error) *MockVoucherShareRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoucherShareRepository_Update_Call) RunAndReturn(run func(context.Context, *models.VoucherShare) error) *MockVoucherShareRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVoucherShareRepository creates a new instance of MockVoucherShareRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoucherShareRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoucherShareRepository {
	mock := &MockVoucherShareRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
