// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	email "savvy/internal/email"
	models "savvy/internal/models"
	services "savvy/internal/services"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockNotificationServiceInterface is an autogenerated mock type for the NotificationServiceInterface type
type MockNotificationServiceInterface struct {
	mock.Mock
}

type MockNotificationServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationServiceInterface) EXPECT() *MockNotificationServiceInterface_Expecter {
	return &MockNotificationServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateShareNotification provides a mock function with given fields: ctx, in
func (_m *MockNotificationServiceInterface) CreateShareNotification(ctx context.Context, in services.ShareNotificationInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateShareNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ShareNotificationInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationServiceInterface_CreateShareNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShareNotification'
type MockNotificationServiceInterface_CreateShareNotification_Call struct {
	*mock.Call
}

// CreateShareNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - in services.ShareNotificationInput
func (_e *MockNotificationServiceInterface_Expecter) CreateShareNotification(ctx interface{}, in interface{}) *MockNotificationServiceInterface_CreateShareNotification_Call {
	return &MockNotificationServiceInterface_CreateShareNotification_Call{Call: _e.mock.On("CreateShareNotification", ctx, in)}
}

func (_c *MockNotificationServiceInterface_CreateShareNotification_Call) Run(run func(ctx context.Context, in services.ShareNotificationInput)) *MockNotificationServiceInterface_CreateShareNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ShareNotificationInput))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_CreateShareNotification_Call) Return(_a0 error) *MockNotificationServiceInterface_CreateShareNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationServiceInterface_CreateShareNotification_Call) RunAndReturn(run func(context.Context, services.ShareNotificationInput) error) *MockNotificationServiceInterface_CreateShareNotification_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransferNotification provides a mock function with given fields: ctx, in
func (_m *MockNotificationServiceInterface) CreateTransferNotification(ctx context.Context, in services.TransferNotificationInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransferNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.TransferNotificationInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationServiceInterface_CreateTransferNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransferNotification'
type MockNotificationServiceInterface_CreateTransferNotification_Call struct {
	*mock.Call
}

// CreateTransferNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - in services.TransferNotificationInput
func (_e *MockNotificationServiceInterface_Expecter) CreateTransferNotification(ctx interface{}, in interface{}) *MockNotificationServiceInterface_CreateTransferNotification_Call {
	return &MockNotificationServiceInterface_CreateTransferNotification_Call{Call: _e.mock.On("CreateTransferNotification", ctx, in)}
}

func (_c *MockNotificationServiceInterface_CreateTransferNotification_Call) Run(run func(ctx context.Context, in services.TransferNotificationInput)) *MockNotificationServiceInterface_CreateTransferNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.TransferNotificationInput))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_CreateTransferNotification_Call) Return(_a0 error) *MockNotificationServiceInterface_CreateTransferNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationServiceInterface_CreateTransferNotification_Call) RunAndReturn(run func(context.Context, services.TransferNotificationInput) error) *MockNotificationServiceInterface_CreateTransferNotification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotification provides a mock function with given fields: ctx, userID, notificationID
func (_m *MockNotificationServiceInterface) DeleteNotification(ctx context.Context, userID uuid.UUID, notificationID uuid.UUID) error {
	ret := _m.Called(ctx, userID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationServiceInterface_DeleteNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotification'
type MockNotificationServiceInterface_DeleteNotification_Call struct {
	*mock.Call
}

// DeleteNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - notificationID uuid.UUID
func (_e *MockNotificationServiceInterface_Expecter) DeleteNotification(ctx interface{}, userID interface{}, notificationID interface{}) *MockNotificationServiceInterface_DeleteNotification_Call {
	return &MockNotificationServiceInterface_DeleteNotification_Call{Call: _e.mock.On("DeleteNotification", ctx, userID, notificationID)}
}

func (_c *MockNotificationServiceInterface_DeleteNotification_Call) Run(run func(ctx context.Context, userID uuid.UUID, notificationID uuid.UUID)) *MockNotificationServiceInterface_DeleteNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_DeleteNotification_Call) Return(_a0 error) *MockNotificationServiceInterface_DeleteNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationServiceInterface_DeleteNotification_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockNotificationServiceInterface_DeleteNotification_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveOldRead provides a mock function with given fields: ctx, olderThanDays
func (_m *MockNotificationServiceInterface) ArchiveOldRead(ctx context.Context, olderThanDays int) (int64, error) {
	ret := _m.Called(ctx, olderThanDays)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveOldRead")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, olderThanDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, olderThanDays)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, olderThanDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationServiceInterface_ArchiveOldRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveOldRead'
type MockNotificationServiceInterface_ArchiveOldRead_Call struct {
	*mock.Call
}

// ArchiveOldRead is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThanDays int
func (_e *MockNotificationServiceInterface_Expecter) ArchiveOldRead(ctx interface{}, olderThanDays interface{}) *MockNotificationServiceInterface_ArchiveOldRead_Call {
	return &MockNotificationServiceInterface_ArchiveOldRead_Call{Call: _e.mock.On("ArchiveOldRead", ctx, olderThanDays)}
}

func (_c *MockNotificationServiceInterface_ArchiveOldRead_Call) Run(run func(ctx context.Context, olderThanDays int)) *MockNotificationServiceInterface_ArchiveOldRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_ArchiveOldRead_Call) Return(_a0 int64, _a1 error) *MockNotificationServiceInterface_ArchiveOldRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationServiceInterface_ArchiveOldRead_Call) RunAndReturn(run func(context.Context, int) (int64, error)) *MockNotificationServiceInterface_ArchiveOldRead_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadCount provides a mock function with given fields: ctx, userID
func (_m *MockNotificationServiceInterface) GetUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationServiceInterface_GetUnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadCount'
type MockNotificationServiceInterface_GetUnreadCount_Call struct {
	*mock.Call
}

// GetUnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockNotificationServiceInterface_Expecter) GetUnreadCount(ctx interface{}, userID interface{}) *MockNotificationServiceInterface_GetUnreadCount_Call {
	return &MockNotificationServiceInterface_GetUnreadCount_Call{Call: _e.mock.On("GetUnreadCount", ctx, userID)}
}

func (_c *MockNotificationServiceInterface_GetUnreadCount_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockNotificationServiceInterface_GetUnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_GetUnreadCount_Call) Return(_a0 int64, _a1 error) *MockNotificationServiceInterface_GetUnreadCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationServiceInterface_GetUnreadCount_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockNotificationServiceInterface_GetUnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserNotifications provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockNotificationServiceInterface) GetUserNotifications(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]models.Notification, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserNotifications")
	}

	var r0 []models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]models.Notification, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []models.Notification); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationServiceInterface_GetUserNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserNotifications'
type MockNotificationServiceInterface_GetUserNotifications_Call struct {
	*mock.Call
}

// GetUserNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockNotificationServiceInterface_Expecter) GetUserNotifications(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockNotificationServiceInterface_GetUserNotifications_Call {
	return &MockNotificationServiceInterface_GetUserNotifications_Call{Call: _e.mock.On("GetUserNotifications", ctx, userID, limit, offset)}
}

func (_c *MockNotificationServiceInterface_GetUserNotifications_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockNotificationServiceInterface_GetUserNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_GetUserNotifications_Call) Return(_a0 []models.Notification, _a1 error) *MockNotificationServiceInterface_GetUserNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationServiceInterface_GetUserNotifications_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]models.Notification, error)) *MockNotificationServiceInterface_GetUserNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllAsRead provides a mock function with given fields: ctx, userID
func (_m *MockNotificationServiceInterface) MarkAllAsRead(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationServiceInterface_MarkAllAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllAsRead'
type MockNotificationServiceInterface_MarkAllAsRead_Call struct {
	*mock.Call
}

// MarkAllAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockNotificationServiceInterface_Expecter) MarkAllAsRead(ctx interface{}, userID interface{}) *MockNotificationServiceInterface_MarkAllAsRead_Call {
	return &MockNotificationServiceInterface_MarkAllAsRead_Call{Call: _e.mock.On("MarkAllAsRead", ctx, userID)}
}

func (_c *MockNotificationServiceInterface_MarkAllAsRead_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockNotificationServiceInterface_MarkAllAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_MarkAllAsRead_Call) Return(_a0 error) *MockNotificationServiceInterface_MarkAllAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationServiceInterface_MarkAllAsRead_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockNotificationServiceInterface_MarkAllAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function with given fields: ctx, userID, notificationID
func (_m *MockNotificationServiceInterface) MarkAsRead(ctx context.Context, userID uuid.UUID, notificationID uuid.UUID) error {
	ret := _m.Called(ctx, userID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationServiceInterface_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockNotificationServiceInterface_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - notificationID uuid.UUID
func (_e *MockNotificationServiceInterface_Expecter) MarkAsRead(ctx interface{}, userID interface{}, notificationID interface{}) *MockNotificationServiceInterface_MarkAsRead_Call {
	return &MockNotificationServiceInterface_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, userID, notificationID)}
}

func (_c *MockNotificationServiceInterface_MarkAsRead_Call) Run(run func(ctx context.Context, userID uuid.UUID, notificationID uuid.UUID)) *MockNotificationServiceInterface_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotificationServiceInterface_MarkAsRead_Call) Return(_a0 error) *MockNotificationServiceInterface_MarkAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationServiceInterface_MarkAsRead_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockNotificationServiceInterface_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// SetEmailService provides a mock function with given fields: emailService, emailTokenService, frontendURL
func (_m *MockNotificationServiceInterface) SetEmailService(emailService email.ServiceInterface, emailTokenService services.EmailTokenServiceInterface, frontendURL string) {
	_m.Called(emailService, emailTokenService, frontendURL)
}

// SetPushService provides a mock function with given fields: pushService
func (_m *MockNotificationServiceInterface) SetPushService(pushService services.PushServiceInterface) {
	_m.Called(pushService)
}

// NewMockNotificationServiceInterface creates a new instance of MockNotificationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationServiceInterface {
	mock := &MockNotificationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
