// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"
	"savvy/internal/repository"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVoucherServiceInterface is an autogenerated mock type for the VoucherServiceInterface type
type MockVoucherServiceInterface struct {
	mock.Mock
}

type MockVoucherServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoucherServiceInterface) EXPECT() *MockVoucherServiceInterface_Expecter {
	return &MockVoucherServiceInterface_Expecter{mock: &_m.Mock}
}

// CountUserVouchers provides a mock function with given fields: ctx, userID
func (_m *MockVoucherServiceInterface) CountUserVouchers(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserVouchers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoucherServiceInterface_CountUserVouchers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserVouchers'
type MockVoucherServiceInterface_CountUserVouchers_Call struct {
	*mock.Call
}

// CountUserVouchers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockVoucherServiceInterface_Expecter) CountUserVouchers(ctx interface{}, userID interface{}) *MockVoucherServiceInterface_CountUserVouchers_Call {
	return &MockVoucherServiceInterface_CountUserVouchers_Call{Call: _e.mock.On("CountUserVouchers", ctx, userID)}
}

func (_c *MockVoucherServiceInterface_CountUserVouchers_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockVoucherServiceInterface_CountUserVouchers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherServiceInterface_CountUserVouchers_Call) Return(_a0 int64, _a1 error) *MockVoucherServiceInterface_CountUserVouchers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoucherServiceInterface_CountUserVouchers_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockVoucherServiceInterface_CountUserVouchers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVoucher provides a mock function with given fields: ctx, voucher
func (_m *MockVoucherServiceInterface) CreateVoucher(ctx context.Context, voucher *models.Voucher) error {
	ret := _m.Called(ctx, voucher)

	if len(ret) == 0 {
		panic("no return value specified for CreateVoucher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Voucher) error); ok {
		r0 = rf(ctx, voucher)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoucherServiceInterface_CreateVoucher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVoucher'
type MockVoucherServiceInterface_CreateVoucher_Call struct {
	*mock.Call
}

// CreateVoucher is a helper method to define mock.On call
//   - ctx context.Context
//   - voucher *models.Voucher
func (_e *MockVoucherServiceInterface_Expecter) CreateVoucher(ctx interface{}, voucher interface{}) *MockVoucherServiceInterface_CreateVoucher_Call {
	return &MockVoucherServiceInterface_CreateVoucher_Call{Call: _e.mock.On("CreateVoucher", ctx, voucher)}
}

func (_c *MockVoucherServiceInterface_CreateVoucher_Call) Run(run func(ctx context.Context, voucher *models.Voucher)) *MockVoucherServiceInterface_CreateVoucher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Voucher))
	})
	return _c
}

func (_c *MockVoucherServiceInterface_CreateVoucher_Call) Return(_a0 error) *MockVoucherServiceInterface_CreateVoucher_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoucherServiceInterface_CreateVoucher_Call) RunAndReturn(run func(context.Context, *models.Voucher) error) *MockVoucherServiceInterface_CreateVoucher_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVoucher provides a mock function with given fields: ctx, id
func (_m *MockVoucherServiceInterface) DeleteVoucher(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVoucher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoucherServiceInterface_DeleteVoucher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVoucher'
type MockVoucherServiceInterface_DeleteVoucher_Call struct {
	*mock.Call
}

// DeleteVoucher is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVoucherServiceInterface_Expecter) DeleteVoucher(ctx interface{}, id interface{}) *MockVoucherServiceInterface_DeleteVoucher_Call {
	return &MockVoucherServiceInterface_DeleteVoucher_Call{Call: _e.mock.On("DeleteVoucher", ctx, id)}
}

func (_c *MockVoucherServiceInterface_DeleteVoucher_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVoucherServiceInterface_DeleteVoucher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherServiceInterface_DeleteVoucher_Call) Return(_a0 error) *MockVoucherServiceInterface_DeleteVoucher_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoucherServiceInterface_DeleteVoucher_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockVoucherServiceInterface_DeleteVoucher_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserVouchersPaginated provides a mock function with given fields: ctx, userID, page, perPage
func (_m *MockVoucherServiceInterface) GetUserVouchersPaginated(ctx context.Context, userID uuid.UUID, page int, perPage int) (*repository.PaginatedResult[models.Voucher], error) {
	ret := _m.Called(ctx, userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetUserVouchersPaginated")
	}

	var r0 *repository.PaginatedResult[models.Voucher]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) (*repository.PaginatedResult[models.Voucher], error)); ok {
		return rf(ctx, userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) *repository.PaginatedResult[models.Voucher]); ok {
		r0 = rf(ctx, userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PaginatedResult[models.Voucher])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserVouchers provides a mock function with given fields: ctx, userID
func (_m *MockVoucherServiceInterface) GetUserVouchers(ctx context.Context, userID uuid.UUID) ([]models.Voucher, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserVouchers")
	}

	var r0 []models.Voucher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Voucher, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Voucher); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Voucher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoucherServiceInterface_GetUserVouchers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserVouchers'
type MockVoucherServiceInterface_GetUserVouchers_Call struct {
	*mock.Call
}

// GetUserVouchers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockVoucherServiceInterface_Expecter) GetUserVouchers(ctx interface{}, userID interface{}) *MockVoucherServiceInterface_GetUserVouchers_Call {
	return &MockVoucherServiceInterface_GetUserVouchers_Call{Call: _e.mock.On("GetUserVouchers", ctx, userID)}
}

func (_c *MockVoucherServiceInterface_GetUserVouchers_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockVoucherServiceInterface_GetUserVouchers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherServiceInterface_GetUserVouchers_Call) Return(_a0 []models.Voucher, _a1 error) *MockVoucherServiceInterface_GetUserVouchers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoucherServiceInterface_GetUserVouchers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Voucher, error)) *MockVoucherServiceInterface_GetUserVouchers_Call {
	_c.Call.Return(run)
	return _c
}

// GetVoucher provides a mock function with given fields: ctx, id
func (_m *MockVoucherServiceInterface) GetVoucher(ctx context.Context, id uuid.UUID) (*models.Voucher, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVoucher")
	}

	var r0 *models.Voucher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Voucher, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Voucher); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Voucher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoucherServiceInterface_GetVoucher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVoucher'
type MockVoucherServiceInterface_GetVoucher_Call struct {
	*mock.Call
}

// GetVoucher is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVoucherServiceInterface_Expecter) GetVoucher(ctx interface{}, id interface{}) *MockVoucherServiceInterface_GetVoucher_Call {
	return &MockVoucherServiceInterface_GetVoucher_Call{Call: _e.mock.On("GetVoucher", ctx, id)}
}

func (_c *MockVoucherServiceInterface_GetVoucher_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVoucherServiceInterface_GetVoucher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoucherServiceInterface_GetVoucher_Call) Return(_a0 *models.Voucher, _a1 error) *MockVoucherServiceInterface_GetVoucher_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoucherServiceInterface_GetVoucher_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Voucher, error)) *MockVoucherServiceInterface_GetVoucher_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVoucher provides a mock function with given fields: ctx, voucher
func (_m *MockVoucherServiceInterface) UpdateVoucher(ctx context.Context, voucher *models.Voucher) error {
	ret := _m.Called(ctx, voucher)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVoucher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Voucher) error); ok {
		r0 = rf(ctx, voucher)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoucherServiceInterface_UpdateVoucher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVoucher'
type MockVoucherServiceInterface_UpdateVoucher_Call struct {
	*mock.Call
}

// UpdateVoucher is a helper method to define mock.On call
//   - ctx context.Context
//   - voucher *models.Voucher
func (_e *MockVoucherServiceInterface_Expecter) UpdateVoucher(ctx interface{}, voucher interface{}) *MockVoucherServiceInterface_UpdateVoucher_Call {
	return &MockVoucherServiceInterface_UpdateVoucher_Call{Call: _e.mock.On("UpdateVoucher", ctx, voucher)}
}

func (_c *MockVoucherServiceInterface_UpdateVoucher_Call) Run(run func(ctx context.Context, voucher *models.Voucher)) *MockVoucherServiceInterface_UpdateVoucher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Voucher))
	})
	return _c
}

func (_c *MockVoucherServiceInterface_UpdateVoucher_Call) Return(_a0 error) *MockVoucherServiceInterface_UpdateVoucher_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoucherServiceInterface_UpdateVoucher_Call) RunAndReturn(run func(context.Context, *models.Voucher) error) *MockVoucherServiceInterface_UpdateVoucher_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVoucherServiceInterface creates a new instance of MockVoucherServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoucherServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoucherServiceInterface {
	mock := &MockVoucherServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CheckDuplicate provides a mock function with given fields: ctx, voucherCode, userID, excludeID
func (m *MockVoucherServiceInterface) CheckDuplicate(ctx context.Context, voucherCode string, userID uuid.UUID, excludeID *uuid.UUID) (*models.Voucher, error) {
	ret := m.Called(ctx, voucherCode, userID, excludeID)
	var r0 *models.Voucher
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, *uuid.UUID) *models.Voucher); ok {
		r0 = rf(ctx, voucherCode, userID, excludeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Voucher)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(ctx, voucherCode, userID, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FindDeletedDuplicate provides a mock function with given fields: ctx, code, userID
func (m *MockVoucherServiceInterface) FindDeletedDuplicate(ctx context.Context, code string, userID uuid.UUID) (*models.Voucher, error) {
	ret := m.Called(ctx, code, userID)
	var r0 *models.Voucher
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *models.Voucher); ok {
		r0 = rf(ctx, code, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Voucher)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, code, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RestoreVoucher provides a mock function with given fields: ctx, id, userID
func (m *MockVoucherServiceInterface) RestoreVoucher(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*models.Voucher, error) {
	ret := m.Called(ctx, id, userID)
	var r0 *models.Voucher
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Voucher); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Voucher)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
