// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCardShareRepository is an autogenerated mock type for the CardShareRepository type
type MockCardShareRepository struct {
	mock.Mock
}

type MockCardShareRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCardShareRepository) EXPECT() *MockCardShareRepository_Expecter {
	return &MockCardShareRepository_Expecter{mock: &_m.Mock}
}

// CountByUser provides a mock function with given fields: ctx, userID
func (_m *MockCardShareRepository) CountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardShareRepository_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type MockCardShareRepository_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCardShareRepository_Expecter) CountByUser(ctx interface{}, userID interface{}) *MockCardShareRepository_CountByUser_Call {
	return &MockCardShareRepository_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID)}
}

func (_c *MockCardShareRepository_CountByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCardShareRepository_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardShareRepository_CountByUser_Call) Return(_a0 int64, _a1 error) *MockCardShareRepository_CountByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardShareRepository_CountByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockCardShareRepository_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, share
func (_m *MockCardShareRepository) Create(ctx context.Context, share *models.CardShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CardShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardShareRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCardShareRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - share *models.CardShare
func (_e *MockCardShareRepository_Expecter) Create(ctx interface{}, share interface{}) *MockCardShareRepository_Create_Call {
	return &MockCardShareRepository_Create_Call{Call: _e.mock.On("Create", ctx, share)}
}

func (_c *MockCardShareRepository_Create_Call) Run(run func(ctx context.Context, share *models.CardShare)) *MockCardShareRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CardShare))
	})
	return _c
}

func (_c *MockCardShareRepository_Create_Call) Return(_a0 error) *MockCardShareRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardShareRepository_Create_Call) RunAndReturn(run func(context.Context, *models.CardShare) error) *MockCardShareRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByCardAndUser provides a mock function with given fields: ctx, cardID, userID
func (_m *MockCardShareRepository) DeleteByCardAndUser(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, cardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCardAndUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, cardID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardShareRepository_DeleteByCardAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCardAndUser'
type MockCardShareRepository_DeleteByCardAndUser_Call struct {
	*mock.Call
}

// DeleteByCardAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - userID uuid.UUID
func (_e *MockCardShareRepository_Expecter) DeleteByCardAndUser(ctx interface{}, cardID interface{}, userID interface{}) *MockCardShareRepository_DeleteByCardAndUser_Call {
	return &MockCardShareRepository_DeleteByCardAndUser_Call{Call: _e.mock.On("DeleteByCardAndUser", ctx, cardID, userID)}
}

func (_c *MockCardShareRepository_DeleteByCardAndUser_Call) Run(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID)) *MockCardShareRepository_DeleteByCardAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardShareRepository_DeleteByCardAndUser_Call) Return(_a0 error) *MockCardShareRepository_DeleteByCardAndUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardShareRepository_DeleteByCardAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockCardShareRepository_DeleteByCardAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByCardID provides a mock function with given fields: ctx, cardID
func (_m *MockCardShareRepository) DeleteByCardID(ctx context.Context, cardID uuid.UUID) error {
	ret := _m.Called(ctx, cardID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCardID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, cardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardShareRepository_DeleteByCardID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCardID'
type MockCardShareRepository_DeleteByCardID_Call struct {
	*mock.Call
}

// DeleteByCardID is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
func (_e *MockCardShareRepository_Expecter) DeleteByCardID(ctx interface{}, cardID interface{}) *MockCardShareRepository_DeleteByCardID_Call {
	return &MockCardShareRepository_DeleteByCardID_Call{Call: _e.mock.On("DeleteByCardID", ctx, cardID)}
}

func (_c *MockCardShareRepository_DeleteByCardID_Call) Run(run func(ctx context.Context, cardID uuid.UUID)) *MockCardShareRepository_DeleteByCardID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardShareRepository_DeleteByCardID_Call) Return(_a0 error) *MockCardShareRepository_DeleteByCardID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardShareRepository_DeleteByCardID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCardShareRepository_DeleteByCardID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCardAndUser provides a mock function with given fields: ctx, cardID, userID
func (_m *MockCardShareRepository) GetByCardAndUser(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) (*models.CardShare, error) {
	ret := _m.Called(ctx, cardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCardAndUser")
	}

	var r0 *models.CardShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.CardShare, error)); ok {
		return rf(ctx, cardID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.CardShare); ok {
		r0 = rf(ctx, cardID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CardShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, cardID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardShareRepository_GetByCardAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCardAndUser'
type MockCardShareRepository_GetByCardAndUser_Call struct {
	*mock.Call
}

// GetByCardAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - userID uuid.UUID
func (_e *MockCardShareRepository_Expecter) GetByCardAndUser(ctx interface{}, cardID interface{}, userID interface{}) *MockCardShareRepository_GetByCardAndUser_Call {
	return &MockCardShareRepository_GetByCardAndUser_Call{Call: _e.mock.On("GetByCardAndUser", ctx, cardID, userID)}
}

func (_c *MockCardShareRepository_GetByCardAndUser_Call) Run(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID)) *MockCardShareRepository_GetByCardAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardShareRepository_GetByCardAndUser_Call) Return(_a0 *models.CardShare, _a1 error) *MockCardShareRepository_GetByCardAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardShareRepository_GetByCardAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.CardShare, error)) *MockCardShareRepository_GetByCardAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCardID provides a mock function with given fields: ctx, cardID
func (_m *MockCardShareRepository) GetByCardID(ctx context.Context, cardID uuid.UUID) ([]models.CardShare, error) {
	ret := _m.Called(ctx, cardID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCardID")
	}

	var r0 []models.CardShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.CardShare, error)); ok {
		return rf(ctx, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.CardShare); ok {
		r0 = rf(ctx, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CardShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardShareRepository_GetByCardID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCardID'
type MockCardShareRepository_GetByCardID_Call struct {
	*mock.Call
}

// GetByCardID is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
func (_e *MockCardShareRepository_Expecter) GetByCardID(ctx interface{}, cardID interface{}) *MockCardShareRepository_GetByCardID_Call {
	return &MockCardShareRepository_GetByCardID_Call{Call: _e.mock.On("GetByCardID", ctx, cardID)}
}

func (_c *MockCardShareRepository_GetByCardID_Call) Run(run func(ctx context.Context, cardID uuid.UUID)) *MockCardShareRepository_GetByCardID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardShareRepository_GetByCardID_Call) Return(_a0 []models.CardShare, _a1 error) *MockCardShareRepository_GetByCardID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardShareRepository_GetByCardID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.CardShare, error)) *MockCardShareRepository_GetByCardID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharedUserIDs provides a mock function with given fields: ctx, ownerID
func (_m *MockCardShareRepository) GetSharedUserIDs(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSharedUserIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardShareRepository_GetSharedUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedUserIDs'
type MockCardShareRepository_GetSharedUserIDs_Call struct {
	*mock.Call
}

// GetSharedUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *MockCardShareRepository_Expecter) GetSharedUserIDs(ctx interface{}, ownerID interface{}) *MockCardShareRepository_GetSharedUserIDs_Call {
	return &MockCardShareRepository_GetSharedUserIDs_Call{Call: _e.mock.On("GetSharedUserIDs", ctx, ownerID)}
}

func (_c *MockCardShareRepository_GetSharedUserIDs_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *MockCardShareRepository_GetSharedUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardShareRepository_GetSharedUserIDs_Call) Return(_a0 []uuid.UUID, _a1 error) *MockCardShareRepository_GetSharedUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardShareRepository_GetSharedUserIDs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *MockCardShareRepository_GetSharedUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, share
func (_m *MockCardShareRepository) Update(ctx context.Context, share *models.CardShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CardShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardShareRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCardShareRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - share *models.CardShare
func (_e *MockCardShareRepository_Expecter) Update(ctx interface{}, share interface{}) *MockCardShareRepository_Update_Call {
	return &MockCardShareRepository_Update_Call{Call: _e.mock.On("Update", ctx, share)}
}

func (_c *MockCardShareRepository_Update_Call) Run(run func(ctx context.Context, share *models.CardShare)) *MockCardShareRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CardShare))
	})
	return _c
}

func (_c *MockCardShareRepository_Update_Call) Return(_a0 error) *MockCardShareRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardShareRepository_Update_Call) RunAndReturn(run func(context.Context, *models.CardShare) error) *MockCardShareRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCardShareRepository creates a new instance of MockCardShareRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCardShareRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCardShareRepository {
	mock := &MockCardShareRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
