// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMerchantServiceInterface is an autogenerated mock type for the MerchantServiceInterface type
type MockMerchantServiceInterface struct {
	mock.Mock
}

type MockMerchantServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchantServiceInterface) EXPECT() *MockMerchantServiceInterface_Expecter {
	return &MockMerchantServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateMerchant provides a mock function with given fields: ctx, merchant
func (_m *MockMerchantServiceInterface) CreateMerchant(ctx context.Context, merchant *models.Merchant) error {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Merchant) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantServiceInterface_CreateMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMerchant'
type MockMerchantServiceInterface_CreateMerchant_Call struct {
	*mock.Call
}

// CreateMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchant *models.Merchant
func (_e *MockMerchantServiceInterface_Expecter) CreateMerchant(ctx interface{}, merchant interface{}) *MockMerchantServiceInterface_CreateMerchant_Call {
	return &MockMerchantServiceInterface_CreateMerchant_Call{Call: _e.mock.On("CreateMerchant", ctx, merchant)}
}

func (_c *MockMerchantServiceInterface_CreateMerchant_Call) Run(run func(ctx context.Context, merchant *models.Merchant)) *MockMerchantServiceInterface_CreateMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Merchant))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_CreateMerchant_Call) Return(_a0 error) *MockMerchantServiceInterface_CreateMerchant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantServiceInterface_CreateMerchant_Call) RunAndReturn(run func(context.Context, *models.Merchant) error) *MockMerchantServiceInterface_CreateMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMerchant provides a mock function with given fields: ctx, id
func (_m *MockMerchantServiceInterface) DeleteMerchant(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantServiceInterface_DeleteMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMerchant'
type MockMerchantServiceInterface_DeleteMerchant_Call struct {
	*mock.Call
}

// DeleteMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantServiceInterface_Expecter) DeleteMerchant(ctx interface{}, id interface{}) *MockMerchantServiceInterface_DeleteMerchant_Call {
	return &MockMerchantServiceInterface_DeleteMerchant_Call{Call: _e.mock.On("DeleteMerchant", ctx, id)}
}

func (_c *MockMerchantServiceInterface_DeleteMerchant_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantServiceInterface_DeleteMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_DeleteMerchant_Call) Return(_a0 error) *MockMerchantServiceInterface_DeleteMerchant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantServiceInterface_DeleteMerchant_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockMerchantServiceInterface_DeleteMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMerchants provides a mock function with given fields: ctx
func (_m *MockMerchantServiceInterface) GetAllMerchants(ctx context.Context) ([]models.Merchant, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMerchants")
	}

	var r0 []models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Merchant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Merchant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantServiceInterface_GetAllMerchants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMerchants'
type MockMerchantServiceInterface_GetAllMerchants_Call struct {
	*mock.Call
}

// GetAllMerchants is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMerchantServiceInterface_Expecter) GetAllMerchants(ctx interface{}) *MockMerchantServiceInterface_GetAllMerchants_Call {
	return &MockMerchantServiceInterface_GetAllMerchants_Call{Call: _e.mock.On("GetAllMerchants", ctx)}
}

func (_c *MockMerchantServiceInterface_GetAllMerchants_Call) Run(run func(ctx context.Context)) *MockMerchantServiceInterface_GetAllMerchants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_GetAllMerchants_Call) Return(_a0 []models.Merchant, _a1 error) *MockMerchantServiceInterface_GetAllMerchants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantServiceInterface_GetAllMerchants_Call) RunAndReturn(run func(context.Context) ([]models.Merchant, error)) *MockMerchantServiceInterface_GetAllMerchants_Call {
	_c.Call.Return(run)
	return _c
}

// GetMerchantByID provides a mock function with given fields: ctx, id
func (_m *MockMerchantServiceInterface) GetMerchantByID(ctx context.Context, id uuid.UUID) (*models.Merchant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantByID")
	}

	var r0 *models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Merchant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Merchant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantServiceInterface_GetMerchantByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchantByID'
type MockMerchantServiceInterface_GetMerchantByID_Call struct {
	*mock.Call
}

// GetMerchantByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantServiceInterface_Expecter) GetMerchantByID(ctx interface{}, id interface{}) *MockMerchantServiceInterface_GetMerchantByID_Call {
	return &MockMerchantServiceInterface_GetMerchantByID_Call{Call: _e.mock.On("GetMerchantByID", ctx, id)}
}

func (_c *MockMerchantServiceInterface_GetMerchantByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantServiceInterface_GetMerchantByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_GetMerchantByID_Call) Return(_a0 *models.Merchant, _a1 error) *MockMerchantServiceInterface_GetMerchantByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantServiceInterface_GetMerchantByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Merchant, error)) *MockMerchantServiceInterface_GetMerchantByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMerchantByName provides a mock function with given fields: ctx, name
func (_m *MockMerchantServiceInterface) GetMerchantByName(ctx context.Context, name string) (*models.Merchant, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantByName")
	}

	var r0 *models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Merchant, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Merchant); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantServiceInterface_GetMerchantByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchantByName'
type MockMerchantServiceInterface_GetMerchantByName_Call struct {
	*mock.Call
}

// GetMerchantByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMerchantServiceInterface_Expecter) GetMerchantByName(ctx interface{}, name interface{}) *MockMerchantServiceInterface_GetMerchantByName_Call {
	return &MockMerchantServiceInterface_GetMerchantByName_Call{Call: _e.mock.On("GetMerchantByName", ctx, name)}
}

func (_c *MockMerchantServiceInterface_GetMerchantByName_Call) Run(run func(ctx context.Context, name string)) *MockMerchantServiceInterface_GetMerchantByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_GetMerchantByName_Call) Return(_a0 *models.Merchant, _a1 error) *MockMerchantServiceInterface_GetMerchantByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantServiceInterface_GetMerchantByName_Call) RunAndReturn(run func(context.Context, string) (*models.Merchant, error)) *MockMerchantServiceInterface_GetMerchantByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetMerchantCount provides a mock function with given fields: ctx
func (_m *MockMerchantServiceInterface) GetMerchantCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantServiceInterface_GetMerchantCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchantCount'
type MockMerchantServiceInterface_GetMerchantCount_Call struct {
	*mock.Call
}

// GetMerchantCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMerchantServiceInterface_Expecter) GetMerchantCount(ctx interface{}) *MockMerchantServiceInterface_GetMerchantCount_Call {
	return &MockMerchantServiceInterface_GetMerchantCount_Call{Call: _e.mock.On("GetMerchantCount", ctx)}
}

func (_c *MockMerchantServiceInterface_GetMerchantCount_Call) Run(run func(ctx context.Context)) *MockMerchantServiceInterface_GetMerchantCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_GetMerchantCount_Call) Return(_a0 int64, _a1 error) *MockMerchantServiceInterface_GetMerchantCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantServiceInterface_GetMerchantCount_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockMerchantServiceInterface_GetMerchantCount_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMerchants provides a mock function with given fields: ctx, query
func (_m *MockMerchantServiceInterface) SearchMerchants(ctx context.Context, query string) ([]models.Merchant, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchMerchants")
	}

	var r0 []models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Merchant, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Merchant); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantServiceInterface_SearchMerchants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMerchants'
type MockMerchantServiceInterface_SearchMerchants_Call struct {
	*mock.Call
}

// SearchMerchants is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockMerchantServiceInterface_Expecter) SearchMerchants(ctx interface{}, query interface{}) *MockMerchantServiceInterface_SearchMerchants_Call {
	return &MockMerchantServiceInterface_SearchMerchants_Call{Call: _e.mock.On("SearchMerchants", ctx, query)}
}

func (_c *MockMerchantServiceInterface_SearchMerchants_Call) Run(run func(ctx context.Context, query string)) *MockMerchantServiceInterface_SearchMerchants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_SearchMerchants_Call) Return(_a0 []models.Merchant, _a1 error) *MockMerchantServiceInterface_SearchMerchants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantServiceInterface_SearchMerchants_Call) RunAndReturn(run func(context.Context, string) ([]models.Merchant, error)) *MockMerchantServiceInterface_SearchMerchants_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMerchant provides a mock function with given fields: ctx, merchant
func (_m *MockMerchantServiceInterface) UpdateMerchant(ctx context.Context, merchant *models.Merchant) error {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Merchant) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantServiceInterface_UpdateMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMerchant'
type MockMerchantServiceInterface_UpdateMerchant_Call struct {
	*mock.Call
}

// UpdateMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchant *models.Merchant
func (_e *MockMerchantServiceInterface_Expecter) UpdateMerchant(ctx interface{}, merchant interface{}) *MockMerchantServiceInterface_UpdateMerchant_Call {
	return &MockMerchantServiceInterface_UpdateMerchant_Call{Call: _e.mock.On("UpdateMerchant", ctx, merchant)}
}

func (_c *MockMerchantServiceInterface_UpdateMerchant_Call) Run(run func(ctx context.Context, merchant *models.Merchant)) *MockMerchantServiceInterface_UpdateMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Merchant))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_UpdateMerchant_Call) Return(_a0 error) *MockMerchantServiceInterface_UpdateMerchant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantServiceInterface_UpdateMerchant_Call) RunAndReturn(run func(context.Context, *models.Merchant) error) *MockMerchantServiceInterface_UpdateMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchantServiceInterface creates a new instance of MockMerchantServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantServiceInterface {
	mock := &MockMerchantServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
