// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFavoriteRepository is an autogenerated mock type for the FavoriteRepository type
type MockFavoriteRepository struct {
	mock.Mock
}

type MockFavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteRepository) EXPECT() *MockFavoriteRepository_Expecter {
	return &MockFavoriteRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, favorite
func (_m *MockFavoriteRepository) Create(ctx context.Context, favorite *models.UserFavorite) error {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserFavorite) error); ok {
		r0 = rf(ctx, favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFavoriteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite *models.UserFavorite
func (_e *MockFavoriteRepository_Expecter) Create(ctx interface{}, favorite interface{}) *MockFavoriteRepository_Create_Call {
	return &MockFavoriteRepository_Create_Call{Call: _e.mock.On("Create", ctx, favorite)}
}

func (_c *MockFavoriteRepository_Create_Call) Run(run func(ctx context.Context, favorite *models.UserFavorite)) *MockFavoriteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserFavorite))
	})
	return _c
}

func (_c *MockFavoriteRepository_Create_Call) Return(_a0 error) *MockFavoriteRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteRepository_Create_Call) RunAndReturn(run func(context.Context, *models.UserFavorite) error) *MockFavoriteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, favorite
func (_m *MockFavoriteRepository) Delete(ctx context.Context, favorite *models.UserFavorite) error {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserFavorite) error); ok {
		r0 = rf(ctx, favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFavoriteRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite *models.UserFavorite
func (_e *MockFavoriteRepository_Expecter) Delete(ctx interface{}, favorite interface{}) *MockFavoriteRepository_Delete_Call {
	return &MockFavoriteRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, favorite)}
}

func (_c *MockFavoriteRepository_Delete_Call) Run(run func(ctx context.Context, favorite *models.UserFavorite)) *MockFavoriteRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserFavorite))
	})
	return _c
}

func (_c *MockFavoriteRepository_Delete_Call) Return(_a0 error) *MockFavoriteRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteRepository_Delete_Call) RunAndReturn(run func(context.Context, *models.UserFavorite) error) *MockFavoriteRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function with given fields: ctx, userID
func (_m *MockFavoriteRepository) GetByUser(ctx context.Context, userID uuid.UUID) ([]models.UserFavorite, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []models.UserFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserFavorite, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserFavorite); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockFavoriteRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockFavoriteRepository_Expecter) GetByUser(ctx interface{}, userID interface{}) *MockFavoriteRepository_GetByUser_Call {
	return &MockFavoriteRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID)}
}

func (_c *MockFavoriteRepository_GetByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockFavoriteRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteRepository_GetByUser_Call) Return(_a0 []models.UserFavorite, _a1 error) *MockFavoriteRepository_GetByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteRepository_GetByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserFavorite, error)) *MockFavoriteRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndResource provides a mock function with given fields: ctx, userID, resourceType, resourceID
func (_m *MockFavoriteRepository) GetByUserAndResource(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID) (*models.UserFavorite, error) {
	ret := _m.Called(ctx, userID, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndResource")
	}

	var r0 *models.UserFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (*models.UserFavorite, error)); ok {
		return rf(ctx, userID, resourceType, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) *models.UserFavorite); ok {
		r0 = rf(ctx, userID, resourceType, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteRepository_GetByUserAndResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndResource'
type MockFavoriteRepository_GetByUserAndResource_Call struct {
	*mock.Call
}

// GetByUserAndResource is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - resourceType string
//   - resourceID uuid.UUID
func (_e *MockFavoriteRepository_Expecter) GetByUserAndResource(ctx interface{}, userID interface{}, resourceType interface{}, resourceID interface{}) *MockFavoriteRepository_GetByUserAndResource_Call {
	return &MockFavoriteRepository_GetByUserAndResource_Call{Call: _e.mock.On("GetByUserAndResource", ctx, userID, resourceType, resourceID)}
}

func (_c *MockFavoriteRepository_GetByUserAndResource_Call) Run(run func(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID)) *MockFavoriteRepository_GetByUserAndResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteRepository_GetByUserAndResource_Call) Return(_a0 *models.UserFavorite, _a1 error) *MockFavoriteRepository_GetByUserAndResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteRepository_GetByUserAndResource_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (*models.UserFavorite, error)) *MockFavoriteRepository_GetByUserAndResource_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavorite provides a mock function with given fields: ctx, userID, resourceType, resourceID
func (_m *MockFavoriteRepository) IsFavorite(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for IsFavorite")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID, resourceType, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID, resourceType, resourceID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteRepository_IsFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavorite'
type MockFavoriteRepository_IsFavorite_Call struct {
	*mock.Call
}

// IsFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - resourceType string
//   - resourceID uuid.UUID
func (_e *MockFavoriteRepository_Expecter) IsFavorite(ctx interface{}, userID interface{}, resourceType interface{}, resourceID interface{}) *MockFavoriteRepository_IsFavorite_Call {
	return &MockFavoriteRepository_IsFavorite_Call{Call: _e.mock.On("IsFavorite", ctx, userID, resourceType, resourceID)}
}

func (_c *MockFavoriteRepository_IsFavorite_Call) Run(run func(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID)) *MockFavoriteRepository_IsFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteRepository_IsFavorite_Call) Return(_a0 bool, _a1 error) *MockFavoriteRepository_IsFavorite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteRepository_IsFavorite_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (bool, error)) *MockFavoriteRepository_IsFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, favorite
func (_m *MockFavoriteRepository) Restore(ctx context.Context, favorite *models.UserFavorite) error {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserFavorite) error); ok {
		r0 = rf(ctx, favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockFavoriteRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite *models.UserFavorite
func (_e *MockFavoriteRepository_Expecter) Restore(ctx interface{}, favorite interface{}) *MockFavoriteRepository_Restore_Call {
	return &MockFavoriteRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, favorite)}
}

func (_c *MockFavoriteRepository_Restore_Call) Run(run func(ctx context.Context, favorite *models.UserFavorite)) *MockFavoriteRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserFavorite))
	})
	return _c
}

func (_c *MockFavoriteRepository_Restore_Call) Return(_a0 error) *MockFavoriteRepository_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteRepository_Restore_Call) RunAndReturn(run func(context.Context, *models.UserFavorite) error) *MockFavoriteRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFavoriteRepository creates a new instance of MockFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteRepository {
	mock := &MockFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
