// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTransferServiceInterface is an autogenerated mock type for the TransferServiceInterface type
type MockTransferServiceInterface struct {
	mock.Mock
}

type MockTransferServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferServiceInterface) EXPECT() *MockTransferServiceInterface_Expecter {
	return &MockTransferServiceInterface_Expecter{mock: &_m.Mock}
}

// TransferCardOwnership provides a mock function with given fields: ctx, cardID, newOwnerID, currentOwnerID
func (_m *MockTransferServiceInterface) TransferCardOwnership(ctx context.Context, cardID uuid.UUID, newOwnerID uuid.UUID, currentOwnerID uuid.UUID) error {
	ret := _m.Called(ctx, cardID, newOwnerID, currentOwnerID)

	if len(ret) == 0 {
		panic("no return value specified for TransferCardOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, cardID, newOwnerID, currentOwnerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferServiceInterface_TransferCardOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferCardOwnership'
type MockTransferServiceInterface_TransferCardOwnership_Call struct {
	*mock.Call
}

// TransferCardOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - newOwnerID uuid.UUID
//   - currentOwnerID uuid.UUID
func (_e *MockTransferServiceInterface_Expecter) TransferCardOwnership(ctx interface{}, cardID interface{}, newOwnerID interface{}, currentOwnerID interface{}) *MockTransferServiceInterface_TransferCardOwnership_Call {
	return &MockTransferServiceInterface_TransferCardOwnership_Call{Call: _e.mock.On("TransferCardOwnership", ctx, cardID, newOwnerID, currentOwnerID)}
}

func (_c *MockTransferServiceInterface_TransferCardOwnership_Call) Run(run func(ctx context.Context, cardID uuid.UUID, newOwnerID uuid.UUID, currentOwnerID uuid.UUID)) *MockTransferServiceInterface_TransferCardOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransferServiceInterface_TransferCardOwnership_Call) Return(_a0 error) *MockTransferServiceInterface_TransferCardOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferServiceInterface_TransferCardOwnership_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockTransferServiceInterface_TransferCardOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// TransferGiftCardOwnership provides a mock function with given fields: ctx, giftCardID, newOwnerID, currentOwnerID
func (_m *MockTransferServiceInterface) TransferGiftCardOwnership(ctx context.Context, giftCardID uuid.UUID, newOwnerID uuid.UUID, currentOwnerID uuid.UUID) error {
	ret := _m.Called(ctx, giftCardID, newOwnerID, currentOwnerID)

	if len(ret) == 0 {
		panic("no return value specified for TransferGiftCardOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, giftCardID, newOwnerID, currentOwnerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferServiceInterface_TransferGiftCardOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferGiftCardOwnership'
type MockTransferServiceInterface_TransferGiftCardOwnership_Call struct {
	*mock.Call
}

// TransferGiftCardOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCardID uuid.UUID
//   - newOwnerID uuid.UUID
//   - currentOwnerID uuid.UUID
func (_e *MockTransferServiceInterface_Expecter) TransferGiftCardOwnership(ctx interface{}, giftCardID interface{}, newOwnerID interface{}, currentOwnerID interface{}) *MockTransferServiceInterface_TransferGiftCardOwnership_Call {
	return &MockTransferServiceInterface_TransferGiftCardOwnership_Call{Call: _e.mock.On("TransferGiftCardOwnership", ctx, giftCardID, newOwnerID, currentOwnerID)}
}

func (_c *MockTransferServiceInterface_TransferGiftCardOwnership_Call) Run(run func(ctx context.Context, giftCardID uuid.UUID, newOwnerID uuid.UUID, currentOwnerID uuid.UUID)) *MockTransferServiceInterface_TransferGiftCardOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransferServiceInterface_TransferGiftCardOwnership_Call) Return(_a0 error) *MockTransferServiceInterface_TransferGiftCardOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferServiceInterface_TransferGiftCardOwnership_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockTransferServiceInterface_TransferGiftCardOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// TransferVoucherOwnership provides a mock function with given fields: ctx, voucherID, newOwnerID, currentOwnerID
func (_m *MockTransferServiceInterface) TransferVoucherOwnership(ctx context.Context, voucherID uuid.UUID, newOwnerID uuid.UUID, currentOwnerID uuid.UUID) error {
	ret := _m.Called(ctx, voucherID, newOwnerID, currentOwnerID)

	if len(ret) == 0 {
		panic("no return value specified for TransferVoucherOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, voucherID, newOwnerID, currentOwnerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferServiceInterface_TransferVoucherOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferVoucherOwnership'
type MockTransferServiceInterface_TransferVoucherOwnership_Call struct {
	*mock.Call
}

// TransferVoucherOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - voucherID uuid.UUID
//   - newOwnerID uuid.UUID
//   - currentOwnerID uuid.UUID
func (_e *MockTransferServiceInterface_Expecter) TransferVoucherOwnership(ctx interface{}, voucherID interface{}, newOwnerID interface{}, currentOwnerID interface{}) *MockTransferServiceInterface_TransferVoucherOwnership_Call {
	return &MockTransferServiceInterface_TransferVoucherOwnership_Call{Call: _e.mock.On("TransferVoucherOwnership", ctx, voucherID, newOwnerID, currentOwnerID)}
}

func (_c *MockTransferServiceInterface_TransferVoucherOwnership_Call) Run(run func(ctx context.Context, voucherID uuid.UUID, newOwnerID uuid.UUID, currentOwnerID uuid.UUID)) *MockTransferServiceInterface_TransferVoucherOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransferServiceInterface_TransferVoucherOwnership_Call) Return(_a0 error) *MockTransferServiceInterface_TransferVoucherOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferServiceInterface_TransferVoucherOwnership_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockTransferServiceInterface_TransferVoucherOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransferServiceInterface creates a new instance of MockTransferServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferServiceInterface {
	mock := &MockTransferServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
