// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	services "savvy/internal/services"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthzServiceInterface is an autogenerated mock type for the AuthzServiceInterface type
type MockAuthzServiceInterface struct {
	mock.Mock
}

type MockAuthzServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthzServiceInterface) EXPECT() *MockAuthzServiceInterface_Expecter {
	return &MockAuthzServiceInterface_Expecter{mock: &_m.Mock}
}

// CheckCardAccess provides a mock function with given fields: ctx, userID, cardID
func (_m *MockAuthzServiceInterface) CheckCardAccess(ctx context.Context, userID uuid.UUID, cardID uuid.UUID) (*services.ResourcePermissions, error) {
	ret := _m.Called(ctx, userID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for CheckCardAccess")
	}

	var r0 *services.ResourcePermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*services.ResourcePermissions, error)); ok {
		return rf(ctx, userID, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *services.ResourcePermissions); ok {
		r0 = rf(ctx, userID, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ResourcePermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthzServiceInterface_CheckCardAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckCardAccess'
type MockAuthzServiceInterface_CheckCardAccess_Call struct {
	*mock.Call
}

// CheckCardAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cardID uuid.UUID
func (_e *MockAuthzServiceInterface_Expecter) CheckCardAccess(ctx interface{}, userID interface{}, cardID interface{}) *MockAuthzServiceInterface_CheckCardAccess_Call {
	return &MockAuthzServiceInterface_CheckCardAccess_Call{Call: _e.mock.On("CheckCardAccess", ctx, userID, cardID)}
}

func (_c *MockAuthzServiceInterface_CheckCardAccess_Call) Run(run func(ctx context.Context, userID uuid.UUID, cardID uuid.UUID)) *MockAuthzServiceInterface_CheckCardAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthzServiceInterface_CheckCardAccess_Call) Return(_a0 *services.ResourcePermissions, _a1 error) *MockAuthzServiceInterface_CheckCardAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthzServiceInterface_CheckCardAccess_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*services.ResourcePermissions, error)) *MockAuthzServiceInterface_CheckCardAccess_Call {
	_c.Call.Return(run)
	return _c
}

// CheckGiftCardAccess provides a mock function with given fields: ctx, userID, giftCardID
func (_m *MockAuthzServiceInterface) CheckGiftCardAccess(ctx context.Context, userID uuid.UUID, giftCardID uuid.UUID) (*services.ResourcePermissions, error) {
	ret := _m.Called(ctx, userID, giftCardID)

	if len(ret) == 0 {
		panic("no return value specified for CheckGiftCardAccess")
	}

	var r0 *services.ResourcePermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*services.ResourcePermissions, error)); ok {
		return rf(ctx, userID, giftCardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *services.ResourcePermissions); ok {
		r0 = rf(ctx, userID, giftCardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ResourcePermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, giftCardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthzServiceInterface_CheckGiftCardAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckGiftCardAccess'
type MockAuthzServiceInterface_CheckGiftCardAccess_Call struct {
	*mock.Call
}

// CheckGiftCardAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - giftCardID uuid.UUID
func (_e *MockAuthzServiceInterface_Expecter) CheckGiftCardAccess(ctx interface{}, userID interface{}, giftCardID interface{}) *MockAuthzServiceInterface_CheckGiftCardAccess_Call {
	return &MockAuthzServiceInterface_CheckGiftCardAccess_Call{Call: _e.mock.On("CheckGiftCardAccess", ctx, userID, giftCardID)}
}

func (_c *MockAuthzServiceInterface_CheckGiftCardAccess_Call) Run(run func(ctx context.Context, userID uuid.UUID, giftCardID uuid.UUID)) *MockAuthzServiceInterface_CheckGiftCardAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthzServiceInterface_CheckGiftCardAccess_Call) Return(_a0 *services.ResourcePermissions, _a1 error) *MockAuthzServiceInterface_CheckGiftCardAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthzServiceInterface_CheckGiftCardAccess_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*services.ResourcePermissions, error)) *MockAuthzServiceInterface_CheckGiftCardAccess_Call {
	_c.Call.Return(run)
	return _c
}

// CheckVoucherAccess provides a mock function with given fields: ctx, userID, voucherID
func (_m *MockAuthzServiceInterface) CheckVoucherAccess(ctx context.Context, userID uuid.UUID, voucherID uuid.UUID) (*services.ResourcePermissions, error) {
	ret := _m.Called(ctx, userID, voucherID)

	if len(ret) == 0 {
		panic("no return value specified for CheckVoucherAccess")
	}

	var r0 *services.ResourcePermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*services.ResourcePermissions, error)); ok {
		return rf(ctx, userID, voucherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *services.ResourcePermissions); ok {
		r0 = rf(ctx, userID, voucherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ResourcePermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, voucherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthzServiceInterface_CheckVoucherAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckVoucherAccess'
type MockAuthzServiceInterface_CheckVoucherAccess_Call struct {
	*mock.Call
}

// CheckVoucherAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - voucherID uuid.UUID
func (_e *MockAuthzServiceInterface_Expecter) CheckVoucherAccess(ctx interface{}, userID interface{}, voucherID interface{}) *MockAuthzServiceInterface_CheckVoucherAccess_Call {
	return &MockAuthzServiceInterface_CheckVoucherAccess_Call{Call: _e.mock.On("CheckVoucherAccess", ctx, userID, voucherID)}
}

func (_c *MockAuthzServiceInterface_CheckVoucherAccess_Call) Run(run func(ctx context.Context, userID uuid.UUID, voucherID uuid.UUID)) *MockAuthzServiceInterface_CheckVoucherAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthzServiceInterface_CheckVoucherAccess_Call) Return(_a0 *services.ResourcePermissions, _a1 error) *MockAuthzServiceInterface_CheckVoucherAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthzServiceInterface_CheckVoucherAccess_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*services.ResourcePermissions, error)) *MockAuthzServiceInterface_CheckVoucherAccess_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthzServiceInterface creates a new instance of MockAuthzServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthzServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthzServiceInterface {
	mock := &MockAuthzServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
