// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"
	repository "savvy/internal/repository"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGiftCardRepository is an autogenerated mock type for the GiftCardRepository type
type MockGiftCardRepository struct {
	mock.Mock
}

type MockGiftCardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGiftCardRepository) EXPECT() *MockGiftCardRepository_Expecter {
	return &MockGiftCardRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardRepository) Count(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockGiftCardRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardRepository_Expecter) Count(ctx interface{}, userID interface{}) *MockGiftCardRepository_Count_Call {
	return &MockGiftCardRepository_Count_Call{Call: _e.mock.On("Count", ctx, userID)}
}

func (_c *MockGiftCardRepository_Count_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardRepository_Count_Call) Return(_a0 int64, _a1 error) *MockGiftCardRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardRepository_Count_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockGiftCardRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, giftCard
func (_m *MockGiftCardRepository) Create(ctx context.Context, giftCard *models.GiftCard) error {
	ret := _m.Called(ctx, giftCard)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCard) error); ok {
		r0 = rf(ctx, giftCard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGiftCardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCard *models.GiftCard
func (_e *MockGiftCardRepository_Expecter) Create(ctx interface{}, giftCard interface{}) *MockGiftCardRepository_Create_Call {
	return &MockGiftCardRepository_Create_Call{Call: _e.mock.On("Create", ctx, giftCard)}
}

func (_c *MockGiftCardRepository_Create_Call) Run(run func(ctx context.Context, giftCard *models.GiftCard)) *MockGiftCardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCard))
	})
	return _c
}

func (_c *MockGiftCardRepository_Create_Call) Return(_a0 error) *MockGiftCardRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardRepository_Create_Call) RunAndReturn(run func(context.Context, *models.GiftCard) error) *MockGiftCardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransaction provides a mock function with given fields: ctx, transaction
func (_m *MockGiftCardRepository) CreateTransaction(ctx context.Context, transaction *models.GiftCardTransaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCardTransaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardRepository_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockGiftCardRepository_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *models.GiftCardTransaction
func (_e *MockGiftCardRepository_Expecter) CreateTransaction(ctx interface{}, transaction interface{}) *MockGiftCardRepository_CreateTransaction_Call {
	return &MockGiftCardRepository_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, transaction)}
}

func (_c *MockGiftCardRepository_CreateTransaction_Call) Run(run func(ctx context.Context, transaction *models.GiftCardTransaction)) *MockGiftCardRepository_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCardTransaction))
	})
	return _c
}

func (_c *MockGiftCardRepository_CreateTransaction_Call) Return(_a0 error) *MockGiftCardRepository_CreateTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardRepository_CreateTransaction_Call) RunAndReturn(run func(context.Context, *models.GiftCardTransaction) error) *MockGiftCardRepository_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockGiftCardRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGiftCardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGiftCardRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockGiftCardRepository_Delete_Call {
	return &MockGiftCardRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockGiftCardRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGiftCardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardRepository_Delete_Call) Return(_a0 error) *MockGiftCardRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGiftCardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransaction provides a mock function with given fields: ctx, transactionID
func (_m *MockGiftCardRepository) DeleteTransaction(ctx context.Context, transactionID uuid.UUID) error {
	ret := _m.Called(ctx, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, transactionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardRepository_DeleteTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransaction'
type MockGiftCardRepository_DeleteTransaction_Call struct {
	*mock.Call
}

// DeleteTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionID uuid.UUID
func (_e *MockGiftCardRepository_Expecter) DeleteTransaction(ctx interface{}, transactionID interface{}) *MockGiftCardRepository_DeleteTransaction_Call {
	return &MockGiftCardRepository_DeleteTransaction_Call{Call: _e.mock.On("DeleteTransaction", ctx, transactionID)}
}

func (_c *MockGiftCardRepository_DeleteTransaction_Call) Run(run func(ctx context.Context, transactionID uuid.UUID)) *MockGiftCardRepository_DeleteTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardRepository_DeleteTransaction_Call) Return(_a0 error) *MockGiftCardRepository_DeleteTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardRepository_DeleteTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGiftCardRepository_DeleteTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, preloads
func (_m *MockGiftCardRepository) GetByID(ctx context.Context, id uuid.UUID, preloads ...string) (*models.GiftCard, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...string) (*models.GiftCard, error)); ok {
		return rf(ctx, id, preloads...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...string) *models.GiftCard); ok {
		r0 = rf(ctx, id, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...string) error); ok {
		r1 = rf(ctx, id, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGiftCardRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - preloads ...string
func (_e *MockGiftCardRepository_Expecter) GetByID(ctx interface{}, id interface{}, preloads ...interface{}) *MockGiftCardRepository_GetByID_Call {
	return &MockGiftCardRepository_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]interface{}{ctx, id}, preloads...)...)}
}

func (_c *MockGiftCardRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, preloads ...string)) *MockGiftCardRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), variadicArgs...)
	})
	return _c
}

func (_c *MockGiftCardRepository_GetByID_Call) Return(_a0 *models.GiftCard, _a1 error) *MockGiftCardRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, ...string) (*models.GiftCard, error)) *MockGiftCardRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]models.GiftCard, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []models.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.GiftCard, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.GiftCard); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockGiftCardRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockGiftCardRepository_GetByUserID_Call {
	return &MockGiftCardRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockGiftCardRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardRepository_GetByUserID_Call) Return(_a0 []models.GiftCard, _a1 error) *MockGiftCardRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.GiftCard, error)) *MockGiftCardRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharedWithUser provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardRepository) GetSharedWithUser(ctx context.Context, userID uuid.UUID) ([]models.GiftCard, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSharedWithUser")
	}

	var r0 []models.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.GiftCard, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.GiftCard); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardRepository_GetSharedWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedWithUser'
type MockGiftCardRepository_GetSharedWithUser_Call struct {
	*mock.Call
}

// GetSharedWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardRepository_Expecter) GetSharedWithUser(ctx interface{}, userID interface{}) *MockGiftCardRepository_GetSharedWithUser_Call {
	return &MockGiftCardRepository_GetSharedWithUser_Call{Call: _e.mock.On("GetSharedWithUser", ctx, userID)}
}

func (_c *MockGiftCardRepository_GetSharedWithUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardRepository_GetSharedWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardRepository_GetSharedWithUser_Call) Return(_a0 []models.GiftCard, _a1 error) *MockGiftCardRepository_GetSharedWithUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardRepository_GetSharedWithUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.GiftCard, error)) *MockGiftCardRepository_GetSharedWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalBalance provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardRepository) GetTotalBalance(ctx context.Context, userID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardRepository_GetTotalBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalBalance'
type MockGiftCardRepository_GetTotalBalance_Call struct {
	*mock.Call
}

// GetTotalBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardRepository_Expecter) GetTotalBalance(ctx interface{}, userID interface{}) *MockGiftCardRepository_GetTotalBalance_Call {
	return &MockGiftCardRepository_GetTotalBalance_Call{Call: _e.mock.On("GetTotalBalance", ctx, userID)}
}

func (_c *MockGiftCardRepository_GetTotalBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardRepository_GetTotalBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardRepository_GetTotalBalance_Call) Return(_a0 float64, _a1 error) *MockGiftCardRepository_GetTotalBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardRepository_GetTotalBalance_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *MockGiftCardRepository_GetTotalBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransaction provides a mock function with given fields: ctx, transactionID, giftCardID
func (_m *MockGiftCardRepository) GetTransaction(ctx context.Context, transactionID uuid.UUID, giftCardID uuid.UUID) (*models.GiftCardTransaction, error) {
	ret := _m.Called(ctx, transactionID, giftCardID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *models.GiftCardTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.GiftCardTransaction, error)); ok {
		return rf(ctx, transactionID, giftCardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.GiftCardTransaction); ok {
		r0 = rf(ctx, transactionID, giftCardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GiftCardTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, transactionID, giftCardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardRepository_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type MockGiftCardRepository_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionID uuid.UUID
//   - giftCardID uuid.UUID
func (_e *MockGiftCardRepository_Expecter) GetTransaction(ctx interface{}, transactionID interface{}, giftCardID interface{}) *MockGiftCardRepository_GetTransaction_Call {
	return &MockGiftCardRepository_GetTransaction_Call{Call: _e.mock.On("GetTransaction", ctx, transactionID, giftCardID)}
}

func (_c *MockGiftCardRepository_GetTransaction_Call) Run(run func(ctx context.Context, transactionID uuid.UUID, giftCardID uuid.UUID)) *MockGiftCardRepository_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardRepository_GetTransaction_Call) Return(_a0 *models.GiftCardTransaction, _a1 error) *MockGiftCardRepository_GetTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardRepository_GetTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.GiftCardTransaction, error)) *MockGiftCardRepository_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, giftCard
func (_m *MockGiftCardRepository) Update(ctx context.Context, giftCard *models.GiftCard) error {
	ret := _m.Called(ctx, giftCard)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCard) error); ok {
		r0 = rf(ctx, giftCard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGiftCardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCard *models.GiftCard
func (_e *MockGiftCardRepository_Expecter) Update(ctx interface{}, giftCard interface{}) *MockGiftCardRepository_Update_Call {
	return &MockGiftCardRepository_Update_Call{Call: _e.mock.On("Update", ctx, giftCard)}
}

func (_c *MockGiftCardRepository_Update_Call) Run(run func(ctx context.Context, giftCard *models.GiftCard)) *MockGiftCardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCard))
	})
	return _c
}

func (_c *MockGiftCardRepository_Update_Call) Return(_a0 error) *MockGiftCardRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardRepository_Update_Call) RunAndReturn(run func(context.Context, *models.GiftCard) error) *MockGiftCardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllForUserPaginated provides a mock function with given fields: ctx, userID, params
func (_m *MockGiftCardRepository) GetAllForUserPaginated(ctx context.Context, userID uuid.UUID, params repository.PaginationParams) (*repository.PaginatedResult[models.GiftCard], error) {
	ret := _m.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAllForUserPaginated")
	}

	var r0 *repository.PaginatedResult[models.GiftCard]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, repository.PaginationParams) (*repository.PaginatedResult[models.GiftCard], error)); ok {
		return rf(ctx, userID, params)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*repository.PaginatedResult[models.GiftCard])
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, repository.PaginationParams) error); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiringGiftCards provides a mock function with given fields: ctx, withinDays
func (_m *MockGiftCardRepository) GetExpiringGiftCards(ctx context.Context, withinDays int) ([]models.GiftCard, error) {
	ret := _m.Called(ctx, withinDays)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringGiftCards")
	}

	var r0 []models.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.GiftCard, error)); ok {
		return rf(ctx, withinDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.GiftCard); ok {
		r0 = rf(ctx, withinDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, withinDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGiftCardRepository creates a new instance of MockGiftCardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGiftCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGiftCardRepository {
	mock := &MockGiftCardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
