// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"
	repository "savvy/internal/repository"
	services "savvy/internal/services"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockAdminServiceInterface is an autogenerated mock type for the AdminServiceInterface type
type MockAdminServiceInterface struct {
	mock.Mock
}

type MockAdminServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminServiceInterface) EXPECT() *MockAdminServiceInterface_Expecter {
	return &MockAdminServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateAuditLog provides a mock function with given fields: ctx, log
func (_m *MockAdminServiceInterface) CreateAuditLog(ctx context.Context, log *models.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_CreateAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditLog'
type MockAdminServiceInterface_CreateAuditLog_Call struct {
	*mock.Call
}

// CreateAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *models.AuditLog
func (_e *MockAdminServiceInterface_Expecter) CreateAuditLog(ctx interface{}, log interface{}) *MockAdminServiceInterface_CreateAuditLog_Call {
	return &MockAdminServiceInterface_CreateAuditLog_Call{Call: _e.mock.On("CreateAuditLog", ctx, log)}
}

func (_c *MockAdminServiceInterface_CreateAuditLog_Call) Run(run func(ctx context.Context, log *models.AuditLog)) *MockAdminServiceInterface_CreateAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.AuditLog))
	})
	return _c
}

func (_c *MockAdminServiceInterface_CreateAuditLog_Call) Return(_a0 error) *MockAdminServiceInterface_CreateAuditLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_CreateAuditLog_Call) RunAndReturn(run func(context.Context, *models.AuditLog) error) *MockAdminServiceInterface_CreateAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLocalUser provides a mock function with given fields: ctx, user
func (_m *MockAdminServiceInterface) CreateLocalUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateLocalUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_CreateLocalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLocalUser'
type MockAdminServiceInterface_CreateLocalUser_Call struct {
	*mock.Call
}

// CreateLocalUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockAdminServiceInterface_Expecter) CreateLocalUser(ctx interface{}, user interface{}) *MockAdminServiceInterface_CreateLocalUser_Call {
	return &MockAdminServiceInterface_CreateLocalUser_Call{Call: _e.mock.On("CreateLocalUser", ctx, user)}
}

func (_c *MockAdminServiceInterface_CreateLocalUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockAdminServiceInterface_CreateLocalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockAdminServiceInterface_CreateLocalUser_Call) Return(_a0 error) *MockAdminServiceInterface_CreateLocalUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_CreateLocalUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockAdminServiceInterface_CreateLocalUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx
func (_m *MockAdminServiceInterface) GetAllUsers(ctx context.Context) ([]models.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServiceInterface_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockAdminServiceInterface_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminServiceInterface_Expecter) GetAllUsers(ctx interface{}) *MockAdminServiceInterface_GetAllUsers_Call {
	return &MockAdminServiceInterface_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *MockAdminServiceInterface_GetAllUsers_Call) Run(run func(ctx context.Context)) *MockAdminServiceInterface_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminServiceInterface_GetAllUsers_Call) Return(_a0 []models.User, _a1 error) *MockAdminServiceInterface_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServiceInterface_GetAllUsers_Call) RunAndReturn(run func(context.Context) ([]models.User, error)) *MockAdminServiceInterface_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuditLogs provides a mock function with given fields: ctx, filters
func (_m *MockAdminServiceInterface) GetAuditLogs(ctx context.Context, filters repository.AuditLogFilters) (*services.AuditLogResult, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditLogs")
	}

	var r0 *services.AuditLogResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditLogFilters) (*services.AuditLogResult, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditLogFilters) *services.AuditLogResult); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.AuditLogResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AuditLogFilters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServiceInterface_GetAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuditLogs'
type MockAdminServiceInterface_GetAuditLogs_Call struct {
	*mock.Call
}

// GetAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repository.AuditLogFilters
func (_e *MockAdminServiceInterface_Expecter) GetAuditLogs(ctx interface{}, filters interface{}) *MockAdminServiceInterface_GetAuditLogs_Call {
	return &MockAdminServiceInterface_GetAuditLogs_Call{Call: _e.mock.On("GetAuditLogs", ctx, filters)}
}

func (_c *MockAdminServiceInterface_GetAuditLogs_Call) Run(run func(ctx context.Context, filters repository.AuditLogFilters)) *MockAdminServiceInterface_GetAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AuditLogFilters))
	})
	return _c
}

func (_c *MockAdminServiceInterface_GetAuditLogs_Call) Return(_a0 *services.AuditLogResult, _a1 error) *MockAdminServiceInterface_GetAuditLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServiceInterface_GetAuditLogs_Call) RunAndReturn(run func(context.Context, repository.AuditLogFilters) (*services.AuditLogResult, error)) *MockAdminServiceInterface_GetAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *MockAdminServiceInterface) GetUserByID(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServiceInterface_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAdminServiceInterface_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminServiceInterface_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockAdminServiceInterface_GetUserByID_Call {
	return &MockAdminServiceInterface_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockAdminServiceInterface_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminServiceInterface_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServiceInterface_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockAdminServiceInterface_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServiceInterface_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.User, error)) *MockAdminServiceInterface_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreResource provides a mock function with given fields: ctx, resourceType, resourceID
func (_m *MockAdminServiceInterface) RestoreResource(ctx context.Context, resourceType string, resourceID uuid.UUID) error {
	ret := _m.Called(ctx, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreResource")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, resourceType, resourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_RestoreResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreResource'
type MockAdminServiceInterface_RestoreResource_Call struct {
	*mock.Call
}

// RestoreResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - resourceID uuid.UUID
func (_e *MockAdminServiceInterface_Expecter) RestoreResource(ctx interface{}, resourceType interface{}, resourceID interface{}) *MockAdminServiceInterface_RestoreResource_Call {
	return &MockAdminServiceInterface_RestoreResource_Call{Call: _e.mock.On("RestoreResource", ctx, resourceType, resourceID)}
}

func (_c *MockAdminServiceInterface_RestoreResource_Call) Run(run func(ctx context.Context, resourceType string, resourceID uuid.UUID)) *MockAdminServiceInterface_RestoreResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServiceInterface_RestoreResource_Call) Return(_a0 error) *MockAdminServiceInterface_RestoreResource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_RestoreResource_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) error) *MockAdminServiceInterface_RestoreResource_Call {
	_c.Call.Return(run)
	return _c
}

// StartImpersonation provides a mock function with given fields: ctx, adminID, targetUserID, resourceData
func (_m *MockAdminServiceInterface) StartImpersonation(ctx context.Context, adminID uuid.UUID, targetUserID uuid.UUID, resourceData interface{}) error {
	ret := _m.Called(ctx, adminID, targetUserID, resourceData)

	if len(ret) == 0 {
		panic("no return value specified for StartImpersonation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, interface{}) error); ok {
		r0 = rf(ctx, adminID, targetUserID, resourceData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_StartImpersonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartImpersonation'
type MockAdminServiceInterface_StartImpersonation_Call struct {
	*mock.Call
}

// StartImpersonation is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - targetUserID uuid.UUID
//   - resourceData interface{}
func (_e *MockAdminServiceInterface_Expecter) StartImpersonation(ctx interface{}, adminID interface{}, targetUserID interface{}, resourceData interface{}) *MockAdminServiceInterface_StartImpersonation_Call {
	return &MockAdminServiceInterface_StartImpersonation_Call{Call: _e.mock.On("StartImpersonation", ctx, adminID, targetUserID, resourceData)}
}

func (_c *MockAdminServiceInterface_StartImpersonation_Call) Run(run func(ctx context.Context, adminID uuid.UUID, targetUserID uuid.UUID, resourceData interface{})) *MockAdminServiceInterface_StartImpersonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(interface{}))
	})
	return _c
}

func (_c *MockAdminServiceInterface_StartImpersonation_Call) Return(_a0 error) *MockAdminServiceInterface_StartImpersonation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_StartImpersonation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, interface{}) error) *MockAdminServiceInterface_StartImpersonation_Call {
	_c.Call.Return(run)
	return _c
}

// StopImpersonation provides a mock function with given fields: ctx, adminID, targetUserID, resourceData
func (_m *MockAdminServiceInterface) StopImpersonation(ctx context.Context, adminID uuid.UUID, targetUserID uuid.UUID, resourceData interface{}) error {
	ret := _m.Called(ctx, adminID, targetUserID, resourceData)

	if len(ret) == 0 {
		panic("no return value specified for StopImpersonation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, interface{}) error); ok {
		r0 = rf(ctx, adminID, targetUserID, resourceData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_StopImpersonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopImpersonation'
type MockAdminServiceInterface_StopImpersonation_Call struct {
	*mock.Call
}

// StopImpersonation is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - targetUserID uuid.UUID
//   - resourceData interface{}
func (_e *MockAdminServiceInterface_Expecter) StopImpersonation(ctx interface{}, adminID interface{}, targetUserID interface{}, resourceData interface{}) *MockAdminServiceInterface_StopImpersonation_Call {
	return &MockAdminServiceInterface_StopImpersonation_Call{Call: _e.mock.On("StopImpersonation", ctx, adminID, targetUserID, resourceData)}
}

func (_c *MockAdminServiceInterface_StopImpersonation_Call) Run(run func(ctx context.Context, adminID uuid.UUID, targetUserID uuid.UUID, resourceData interface{})) *MockAdminServiceInterface_StopImpersonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(interface{}))
	})
	return _c
}

func (_c *MockAdminServiceInterface_StopImpersonation_Call) Return(_a0 error) *MockAdminServiceInterface_StopImpersonation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_StopImpersonation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, interface{}) error) *MockAdminServiceInterface_StopImpersonation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, userID, email, firstName, lastName, role
func (_m *MockAdminServiceInterface) UpdateUser(ctx context.Context, userID uuid.UUID, email string, firstName string, lastName string, role string) error {
	ret := _m.Called(ctx, userID, email, firstName, lastName, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, email, firstName, lastName, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockAdminServiceInterface_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - email string
//   - firstName string
//   - lastName string
//   - role string
func (_e *MockAdminServiceInterface_Expecter) UpdateUser(ctx interface{}, userID interface{}, email interface{}, firstName interface{}, lastName interface{}, role interface{}) *MockAdminServiceInterface_UpdateUser_Call {
	return &MockAdminServiceInterface_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, userID, email, firstName, lastName, role)}
}

func (_c *MockAdminServiceInterface_UpdateUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, email string, firstName string, lastName string, role string)) *MockAdminServiceInterface_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockAdminServiceInterface_UpdateUser_Call) Return(_a0 error) *MockAdminServiceInterface_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_UpdateUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, string) error) *MockAdminServiceInterface_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserRole provides a mock function with given fields: ctx, userID, newRole
func (_m *MockAdminServiceInterface) UpdateUserRole(ctx context.Context, userID uuid.UUID, newRole string) error {
	ret := _m.Called(ctx, userID, newRole)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, newRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_UpdateUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserRole'
type MockAdminServiceInterface_UpdateUserRole_Call struct {
	*mock.Call
}

// UpdateUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - newRole string
func (_e *MockAdminServiceInterface_Expecter) UpdateUserRole(ctx interface{}, userID interface{}, newRole interface{}) *MockAdminServiceInterface_UpdateUserRole_Call {
	return &MockAdminServiceInterface_UpdateUserRole_Call{Call: _e.mock.On("UpdateUserRole", ctx, userID, newRole)}
}

func (_c *MockAdminServiceInterface_UpdateUserRole_Call) Run(run func(ctx context.Context, userID uuid.UUID, newRole string)) *MockAdminServiceInterface_UpdateUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockAdminServiceInterface_UpdateUserRole_Call) Return(_a0 error) *MockAdminServiceInterface_UpdateUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_UpdateUserRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockAdminServiceInterface_UpdateUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateImpersonation provides a mock function with given fields: ctx, adminID, targetUserID
func (_m *MockAdminServiceInterface) ValidateImpersonation(ctx context.Context, adminID uuid.UUID, targetUserID uuid.UUID) error {
	ret := _m.Called(ctx, adminID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateImpersonation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, adminID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServiceInterface_ValidateImpersonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateImpersonation'
type MockAdminServiceInterface_ValidateImpersonation_Call struct {
	*mock.Call
}

// ValidateImpersonation is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - targetUserID uuid.UUID
func (_e *MockAdminServiceInterface_Expecter) ValidateImpersonation(ctx interface{}, adminID interface{}, targetUserID interface{}) *MockAdminServiceInterface_ValidateImpersonation_Call {
	return &MockAdminServiceInterface_ValidateImpersonation_Call{Call: _e.mock.On("ValidateImpersonation", ctx, adminID, targetUserID)}
}

func (_c *MockAdminServiceInterface_ValidateImpersonation_Call) Run(run func(ctx context.Context, adminID uuid.UUID, targetUserID uuid.UUID)) *MockAdminServiceInterface_ValidateImpersonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServiceInterface_ValidateImpersonation_Call) Return(_a0 error) *MockAdminServiceInterface_ValidateImpersonation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServiceInterface_ValidateImpersonation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockAdminServiceInterface_ValidateImpersonation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminServiceInterface creates a new instance of MockAdminServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminServiceInterface {
	mock := &MockAdminServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
