// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"
	"savvy/internal/repository"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGiftCardServiceInterface is an autogenerated mock type for the GiftCardServiceInterface type
type MockGiftCardServiceInterface struct {
	mock.Mock
}

type MockGiftCardServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGiftCardServiceInterface) EXPECT() *MockGiftCardServiceInterface_Expecter {
	return &MockGiftCardServiceInterface_Expecter{mock: &_m.Mock}
}

// CanUserAccessGiftCard provides a mock function with given fields: ctx, giftCardID, userID
func (_m *MockGiftCardServiceInterface) CanUserAccessGiftCard(ctx context.Context, giftCardID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, giftCardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanUserAccessGiftCard")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, giftCardID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, giftCardID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, giftCardID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardServiceInterface_CanUserAccessGiftCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanUserAccessGiftCard'
type MockGiftCardServiceInterface_CanUserAccessGiftCard_Call struct {
	*mock.Call
}

// CanUserAccessGiftCard is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCardID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) CanUserAccessGiftCard(ctx interface{}, giftCardID interface{}, userID interface{}) *MockGiftCardServiceInterface_CanUserAccessGiftCard_Call {
	return &MockGiftCardServiceInterface_CanUserAccessGiftCard_Call{Call: _e.mock.On("CanUserAccessGiftCard", ctx, giftCardID, userID)}
}

func (_c *MockGiftCardServiceInterface_CanUserAccessGiftCard_Call) Run(run func(ctx context.Context, giftCardID uuid.UUID, userID uuid.UUID)) *MockGiftCardServiceInterface_CanUserAccessGiftCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_CanUserAccessGiftCard_Call) Return(_a0 bool, _a1 error) *MockGiftCardServiceInterface_CanUserAccessGiftCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardServiceInterface_CanUserAccessGiftCard_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockGiftCardServiceInterface_CanUserAccessGiftCard_Call {
	_c.Call.Return(run)
	return _c
}

// CountUserGiftCards provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardServiceInterface) CountUserGiftCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserGiftCards")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardServiceInterface_CountUserGiftCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserGiftCards'
type MockGiftCardServiceInterface_CountUserGiftCards_Call struct {
	*mock.Call
}

// CountUserGiftCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) CountUserGiftCards(ctx interface{}, userID interface{}) *MockGiftCardServiceInterface_CountUserGiftCards_Call {
	return &MockGiftCardServiceInterface_CountUserGiftCards_Call{Call: _e.mock.On("CountUserGiftCards", ctx, userID)}
}

func (_c *MockGiftCardServiceInterface_CountUserGiftCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardServiceInterface_CountUserGiftCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_CountUserGiftCards_Call) Return(_a0 int64, _a1 error) *MockGiftCardServiceInterface_CountUserGiftCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardServiceInterface_CountUserGiftCards_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockGiftCardServiceInterface_CountUserGiftCards_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGiftCard provides a mock function with given fields: ctx, giftCard
func (_m *MockGiftCardServiceInterface) CreateGiftCard(ctx context.Context, giftCard *models.GiftCard) error {
	ret := _m.Called(ctx, giftCard)

	if len(ret) == 0 {
		panic("no return value specified for CreateGiftCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCard) error); ok {
		r0 = rf(ctx, giftCard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardServiceInterface_CreateGiftCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGiftCard'
type MockGiftCardServiceInterface_CreateGiftCard_Call struct {
	*mock.Call
}

// CreateGiftCard is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCard *models.GiftCard
func (_e *MockGiftCardServiceInterface_Expecter) CreateGiftCard(ctx interface{}, giftCard interface{}) *MockGiftCardServiceInterface_CreateGiftCard_Call {
	return &MockGiftCardServiceInterface_CreateGiftCard_Call{Call: _e.mock.On("CreateGiftCard", ctx, giftCard)}
}

func (_c *MockGiftCardServiceInterface_CreateGiftCard_Call) Run(run func(ctx context.Context, giftCard *models.GiftCard)) *MockGiftCardServiceInterface_CreateGiftCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCard))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_CreateGiftCard_Call) Return(_a0 error) *MockGiftCardServiceInterface_CreateGiftCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardServiceInterface_CreateGiftCard_Call) RunAndReturn(run func(context.Context, *models.GiftCard) error) *MockGiftCardServiceInterface_CreateGiftCard_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransaction provides a mock function with given fields: ctx, transaction
func (_m *MockGiftCardServiceInterface) CreateTransaction(ctx context.Context, transaction *models.GiftCardTransaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCardTransaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardServiceInterface_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockGiftCardServiceInterface_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *models.GiftCardTransaction
func (_e *MockGiftCardServiceInterface_Expecter) CreateTransaction(ctx interface{}, transaction interface{}) *MockGiftCardServiceInterface_CreateTransaction_Call {
	return &MockGiftCardServiceInterface_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, transaction)}
}

func (_c *MockGiftCardServiceInterface_CreateTransaction_Call) Run(run func(ctx context.Context, transaction *models.GiftCardTransaction)) *MockGiftCardServiceInterface_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCardTransaction))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_CreateTransaction_Call) Return(_a0 error) *MockGiftCardServiceInterface_CreateTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardServiceInterface_CreateTransaction_Call) RunAndReturn(run func(context.Context, *models.GiftCardTransaction) error) *MockGiftCardServiceInterface_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGiftCard provides a mock function with given fields: ctx, id
func (_m *MockGiftCardServiceInterface) DeleteGiftCard(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGiftCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardServiceInterface_DeleteGiftCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGiftCard'
type MockGiftCardServiceInterface_DeleteGiftCard_Call struct {
	*mock.Call
}

// DeleteGiftCard is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) DeleteGiftCard(ctx interface{}, id interface{}) *MockGiftCardServiceInterface_DeleteGiftCard_Call {
	return &MockGiftCardServiceInterface_DeleteGiftCard_Call{Call: _e.mock.On("DeleteGiftCard", ctx, id)}
}

func (_c *MockGiftCardServiceInterface_DeleteGiftCard_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGiftCardServiceInterface_DeleteGiftCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_DeleteGiftCard_Call) Return(_a0 error) *MockGiftCardServiceInterface_DeleteGiftCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardServiceInterface_DeleteGiftCard_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGiftCardServiceInterface_DeleteGiftCard_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransaction provides a mock function with given fields: ctx, transactionID
func (_m *MockGiftCardServiceInterface) DeleteTransaction(ctx context.Context, transactionID uuid.UUID) error {
	ret := _m.Called(ctx, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, transactionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardServiceInterface_DeleteTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransaction'
type MockGiftCardServiceInterface_DeleteTransaction_Call struct {
	*mock.Call
}

// DeleteTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionID uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) DeleteTransaction(ctx interface{}, transactionID interface{}) *MockGiftCardServiceInterface_DeleteTransaction_Call {
	return &MockGiftCardServiceInterface_DeleteTransaction_Call{Call: _e.mock.On("DeleteTransaction", ctx, transactionID)}
}

func (_c *MockGiftCardServiceInterface_DeleteTransaction_Call) Run(run func(ctx context.Context, transactionID uuid.UUID)) *MockGiftCardServiceInterface_DeleteTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_DeleteTransaction_Call) Return(_a0 error) *MockGiftCardServiceInterface_DeleteTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardServiceInterface_DeleteTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGiftCardServiceInterface_DeleteTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentBalance provides a mock function with given fields: ctx, giftCardID
func (_m *MockGiftCardServiceInterface) GetCurrentBalance(ctx context.Context, giftCardID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, giftCardID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, giftCardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, giftCardID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, giftCardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardServiceInterface_GetCurrentBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentBalance'
type MockGiftCardServiceInterface_GetCurrentBalance_Call struct {
	*mock.Call
}

// GetCurrentBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCardID uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) GetCurrentBalance(ctx interface{}, giftCardID interface{}) *MockGiftCardServiceInterface_GetCurrentBalance_Call {
	return &MockGiftCardServiceInterface_GetCurrentBalance_Call{Call: _e.mock.On("GetCurrentBalance", ctx, giftCardID)}
}

func (_c *MockGiftCardServiceInterface_GetCurrentBalance_Call) Run(run func(ctx context.Context, giftCardID uuid.UUID)) *MockGiftCardServiceInterface_GetCurrentBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_GetCurrentBalance_Call) Return(_a0 float64, _a1 error) *MockGiftCardServiceInterface_GetCurrentBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardServiceInterface_GetCurrentBalance_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *MockGiftCardServiceInterface_GetCurrentBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetGiftCard provides a mock function with given fields: ctx, id
func (_m *MockGiftCardServiceInterface) GetGiftCard(ctx context.Context, id uuid.UUID) (*models.GiftCard, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGiftCard")
	}

	var r0 *models.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.GiftCard, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.GiftCard); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardServiceInterface_GetGiftCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGiftCard'
type MockGiftCardServiceInterface_GetGiftCard_Call struct {
	*mock.Call
}

// GetGiftCard is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) GetGiftCard(ctx interface{}, id interface{}) *MockGiftCardServiceInterface_GetGiftCard_Call {
	return &MockGiftCardServiceInterface_GetGiftCard_Call{Call: _e.mock.On("GetGiftCard", ctx, id)}
}

func (_c *MockGiftCardServiceInterface_GetGiftCard_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGiftCardServiceInterface_GetGiftCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_GetGiftCard_Call) Return(_a0 *models.GiftCard, _a1 error) *MockGiftCardServiceInterface_GetGiftCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardServiceInterface_GetGiftCard_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.GiftCard, error)) *MockGiftCardServiceInterface_GetGiftCard_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalBalance provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardServiceInterface) GetTotalBalance(ctx context.Context, userID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardServiceInterface_GetTotalBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalBalance'
type MockGiftCardServiceInterface_GetTotalBalance_Call struct {
	*mock.Call
}

// GetTotalBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) GetTotalBalance(ctx interface{}, userID interface{}) *MockGiftCardServiceInterface_GetTotalBalance_Call {
	return &MockGiftCardServiceInterface_GetTotalBalance_Call{Call: _e.mock.On("GetTotalBalance", ctx, userID)}
}

func (_c *MockGiftCardServiceInterface_GetTotalBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardServiceInterface_GetTotalBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_GetTotalBalance_Call) Return(_a0 float64, _a1 error) *MockGiftCardServiceInterface_GetTotalBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardServiceInterface_GetTotalBalance_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *MockGiftCardServiceInterface_GetTotalBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransaction provides a mock function with given fields: ctx, transactionID, giftCardID
func (_m *MockGiftCardServiceInterface) GetTransaction(ctx context.Context, transactionID uuid.UUID, giftCardID uuid.UUID) (*models.GiftCardTransaction, error) {
	ret := _m.Called(ctx, transactionID, giftCardID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *models.GiftCardTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.GiftCardTransaction, error)); ok {
		return rf(ctx, transactionID, giftCardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.GiftCardTransaction); ok {
		r0 = rf(ctx, transactionID, giftCardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GiftCardTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, transactionID, giftCardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardServiceInterface_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type MockGiftCardServiceInterface_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionID uuid.UUID
//   - giftCardID uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) GetTransaction(ctx interface{}, transactionID interface{}, giftCardID interface{}) *MockGiftCardServiceInterface_GetTransaction_Call {
	return &MockGiftCardServiceInterface_GetTransaction_Call{Call: _e.mock.On("GetTransaction", ctx, transactionID, giftCardID)}
}

func (_c *MockGiftCardServiceInterface_GetTransaction_Call) Run(run func(ctx context.Context, transactionID uuid.UUID, giftCardID uuid.UUID)) *MockGiftCardServiceInterface_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_GetTransaction_Call) Return(_a0 *models.GiftCardTransaction, _a1 error) *MockGiftCardServiceInterface_GetTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardServiceInterface_GetTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.GiftCardTransaction, error)) *MockGiftCardServiceInterface_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGiftCardsPaginated provides a mock function with given fields: ctx, userID, page, perPage
func (_m *MockGiftCardServiceInterface) GetUserGiftCardsPaginated(ctx context.Context, userID uuid.UUID, page int, perPage int) (*repository.PaginatedResult[models.GiftCard], error) {
	ret := _m.Called(ctx, userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGiftCardsPaginated")
	}

	var r0 *repository.PaginatedResult[models.GiftCard]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) (*repository.PaginatedResult[models.GiftCard], error)); ok {
		return rf(ctx, userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) *repository.PaginatedResult[models.GiftCard]); ok {
		r0 = rf(ctx, userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PaginatedResult[models.GiftCard])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserGiftCards provides a mock function with given fields: ctx, userID
func (_m *MockGiftCardServiceInterface) GetUserGiftCards(ctx context.Context, userID uuid.UUID) ([]models.GiftCard, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGiftCards")
	}

	var r0 []models.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.GiftCard, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.GiftCard); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGiftCardServiceInterface_GetUserGiftCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGiftCards'
type MockGiftCardServiceInterface_GetUserGiftCards_Call struct {
	*mock.Call
}

// GetUserGiftCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGiftCardServiceInterface_Expecter) GetUserGiftCards(ctx interface{}, userID interface{}) *MockGiftCardServiceInterface_GetUserGiftCards_Call {
	return &MockGiftCardServiceInterface_GetUserGiftCards_Call{Call: _e.mock.On("GetUserGiftCards", ctx, userID)}
}

func (_c *MockGiftCardServiceInterface_GetUserGiftCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGiftCardServiceInterface_GetUserGiftCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_GetUserGiftCards_Call) Return(_a0 []models.GiftCard, _a1 error) *MockGiftCardServiceInterface_GetUserGiftCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGiftCardServiceInterface_GetUserGiftCards_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.GiftCard, error)) *MockGiftCardServiceInterface_GetUserGiftCards_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGiftCard provides a mock function with given fields: ctx, giftCard
func (_m *MockGiftCardServiceInterface) UpdateGiftCard(ctx context.Context, giftCard *models.GiftCard) error {
	ret := _m.Called(ctx, giftCard)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGiftCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftCard) error); ok {
		r0 = rf(ctx, giftCard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGiftCardServiceInterface_UpdateGiftCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGiftCard'
type MockGiftCardServiceInterface_UpdateGiftCard_Call struct {
	*mock.Call
}

// UpdateGiftCard is a helper method to define mock.On call
//   - ctx context.Context
//   - giftCard *models.GiftCard
func (_e *MockGiftCardServiceInterface_Expecter) UpdateGiftCard(ctx interface{}, giftCard interface{}) *MockGiftCardServiceInterface_UpdateGiftCard_Call {
	return &MockGiftCardServiceInterface_UpdateGiftCard_Call{Call: _e.mock.On("UpdateGiftCard", ctx, giftCard)}
}

func (_c *MockGiftCardServiceInterface_UpdateGiftCard_Call) Run(run func(ctx context.Context, giftCard *models.GiftCard)) *MockGiftCardServiceInterface_UpdateGiftCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftCard))
	})
	return _c
}

func (_c *MockGiftCardServiceInterface_UpdateGiftCard_Call) Return(_a0 error) *MockGiftCardServiceInterface_UpdateGiftCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGiftCardServiceInterface_UpdateGiftCard_Call) RunAndReturn(run func(context.Context, *models.GiftCard) error) *MockGiftCardServiceInterface_UpdateGiftCard_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGiftCardServiceInterface creates a new instance of MockGiftCardServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGiftCardServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGiftCardServiceInterface {
	mock := &MockGiftCardServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CheckDuplicate provides a mock function with given fields: ctx, cardNumber, userID, excludeID
func (m *MockGiftCardServiceInterface) CheckDuplicate(ctx context.Context, cardNumber string, userID uuid.UUID, excludeID *uuid.UUID) (*models.GiftCard, error) {
	ret := m.Called(ctx, cardNumber, userID, excludeID)
	var r0 *models.GiftCard
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, *uuid.UUID) *models.GiftCard); ok {
		r0 = rf(ctx, cardNumber, userID, excludeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GiftCard)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(ctx, cardNumber, userID, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
