// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFavoriteServiceInterface is an autogenerated mock type for the FavoriteServiceInterface type
type MockFavoriteServiceInterface struct {
	mock.Mock
}

type MockFavoriteServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteServiceInterface) EXPECT() *MockFavoriteServiceInterface_Expecter {
	return &MockFavoriteServiceInterface_Expecter{mock: &_m.Mock}
}

// GetFavoriteCards provides a mock function with given fields: ctx, userID
func (_m *MockFavoriteServiceInterface) GetFavoriteCards(ctx context.Context, userID uuid.UUID) ([]models.Card, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFavoriteCards")
	}

	var r0 []models.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Card, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Card); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteServiceInterface_GetFavoriteCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavoriteCards'
type MockFavoriteServiceInterface_GetFavoriteCards_Call struct {
	*mock.Call
}

// GetFavoriteCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockFavoriteServiceInterface_Expecter) GetFavoriteCards(ctx interface{}, userID interface{}) *MockFavoriteServiceInterface_GetFavoriteCards_Call {
	return &MockFavoriteServiceInterface_GetFavoriteCards_Call{Call: _e.mock.On("GetFavoriteCards", ctx, userID)}
}

func (_c *MockFavoriteServiceInterface_GetFavoriteCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockFavoriteServiceInterface_GetFavoriteCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavoriteCards_Call) Return(_a0 []models.Card, _a1 error) *MockFavoriteServiceInterface_GetFavoriteCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavoriteCards_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Card, error)) *MockFavoriteServiceInterface_GetFavoriteCards_Call {
	_c.Call.Return(run)
	return _c
}

// GetFavoriteGiftCards provides a mock function with given fields: ctx, userID
func (_m *MockFavoriteServiceInterface) GetFavoriteGiftCards(ctx context.Context, userID uuid.UUID) ([]models.GiftCard, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFavoriteGiftCards")
	}

	var r0 []models.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.GiftCard, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.GiftCard); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteServiceInterface_GetFavoriteGiftCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavoriteGiftCards'
type MockFavoriteServiceInterface_GetFavoriteGiftCards_Call struct {
	*mock.Call
}

// GetFavoriteGiftCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockFavoriteServiceInterface_Expecter) GetFavoriteGiftCards(ctx interface{}, userID interface{}) *MockFavoriteServiceInterface_GetFavoriteGiftCards_Call {
	return &MockFavoriteServiceInterface_GetFavoriteGiftCards_Call{Call: _e.mock.On("GetFavoriteGiftCards", ctx, userID)}
}

func (_c *MockFavoriteServiceInterface_GetFavoriteGiftCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockFavoriteServiceInterface_GetFavoriteGiftCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavoriteGiftCards_Call) Return(_a0 []models.GiftCard, _a1 error) *MockFavoriteServiceInterface_GetFavoriteGiftCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavoriteGiftCards_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.GiftCard, error)) *MockFavoriteServiceInterface_GetFavoriteGiftCards_Call {
	_c.Call.Return(run)
	return _c
}

// GetFavoriteVouchers provides a mock function with given fields: ctx, userID
func (_m *MockFavoriteServiceInterface) GetFavoriteVouchers(ctx context.Context, userID uuid.UUID) ([]models.Voucher, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFavoriteVouchers")
	}

	var r0 []models.Voucher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Voucher, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Voucher); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Voucher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteServiceInterface_GetFavoriteVouchers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavoriteVouchers'
type MockFavoriteServiceInterface_GetFavoriteVouchers_Call struct {
	*mock.Call
}

// GetFavoriteVouchers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockFavoriteServiceInterface_Expecter) GetFavoriteVouchers(ctx interface{}, userID interface{}) *MockFavoriteServiceInterface_GetFavoriteVouchers_Call {
	return &MockFavoriteServiceInterface_GetFavoriteVouchers_Call{Call: _e.mock.On("GetFavoriteVouchers", ctx, userID)}
}

func (_c *MockFavoriteServiceInterface_GetFavoriteVouchers_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockFavoriteServiceInterface_GetFavoriteVouchers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavoriteVouchers_Call) Return(_a0 []models.Voucher, _a1 error) *MockFavoriteServiceInterface_GetFavoriteVouchers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavoriteVouchers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Voucher, error)) *MockFavoriteServiceInterface_GetFavoriteVouchers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserFavorites provides a mock function with given fields: ctx, userID
func (_m *MockFavoriteServiceInterface) GetUserFavorites(ctx context.Context, userID uuid.UUID) ([]models.UserFavorite, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFavorites")
	}

	var r0 []models.UserFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserFavorite, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserFavorite); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteServiceInterface_GetUserFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFavorites'
type MockFavoriteServiceInterface_GetUserFavorites_Call struct {
	*mock.Call
}

// GetUserFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockFavoriteServiceInterface_Expecter) GetUserFavorites(ctx interface{}, userID interface{}) *MockFavoriteServiceInterface_GetUserFavorites_Call {
	return &MockFavoriteServiceInterface_GetUserFavorites_Call{Call: _e.mock.On("GetUserFavorites", ctx, userID)}
}

func (_c *MockFavoriteServiceInterface_GetUserFavorites_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockFavoriteServiceInterface_GetUserFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_GetUserFavorites_Call) Return(_a0 []models.UserFavorite, _a1 error) *MockFavoriteServiceInterface_GetUserFavorites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteServiceInterface_GetUserFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserFavorite, error)) *MockFavoriteServiceInterface_GetUserFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavorite provides a mock function with given fields: ctx, userID, resourceType, resourceID
func (_m *MockFavoriteServiceInterface) IsFavorite(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for IsFavorite")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID, resourceType, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID, resourceType, resourceID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteServiceInterface_IsFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavorite'
type MockFavoriteServiceInterface_IsFavorite_Call struct {
	*mock.Call
}

// IsFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - resourceType string
//   - resourceID uuid.UUID
func (_e *MockFavoriteServiceInterface_Expecter) IsFavorite(ctx interface{}, userID interface{}, resourceType interface{}, resourceID interface{}) *MockFavoriteServiceInterface_IsFavorite_Call {
	return &MockFavoriteServiceInterface_IsFavorite_Call{Call: _e.mock.On("IsFavorite", ctx, userID, resourceType, resourceID)}
}

func (_c *MockFavoriteServiceInterface_IsFavorite_Call) Run(run func(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID)) *MockFavoriteServiceInterface_IsFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_IsFavorite_Call) Return(_a0 bool, _a1 error) *MockFavoriteServiceInterface_IsFavorite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteServiceInterface_IsFavorite_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (bool, error)) *MockFavoriteServiceInterface_IsFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleFavorite provides a mock function with given fields: ctx, userID, resourceType, resourceID
func (_m *MockFavoriteServiceInterface) ToggleFavorite(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID) error {
	ret := _m.Called(ctx, userID, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleFavorite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, resourceType, resourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteServiceInterface_ToggleFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleFavorite'
type MockFavoriteServiceInterface_ToggleFavorite_Call struct {
	*mock.Call
}

// ToggleFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - resourceType string
//   - resourceID uuid.UUID
func (_e *MockFavoriteServiceInterface_Expecter) ToggleFavorite(ctx interface{}, userID interface{}, resourceType interface{}, resourceID interface{}) *MockFavoriteServiceInterface_ToggleFavorite_Call {
	return &MockFavoriteServiceInterface_ToggleFavorite_Call{Call: _e.mock.On("ToggleFavorite", ctx, userID, resourceType, resourceID)}
}

func (_c *MockFavoriteServiceInterface_ToggleFavorite_Call) Run(run func(ctx context.Context, userID uuid.UUID, resourceType string, resourceID uuid.UUID)) *MockFavoriteServiceInterface_ToggleFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_ToggleFavorite_Call) Return(_a0 error) *MockFavoriteServiceInterface_ToggleFavorite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteServiceInterface_ToggleFavorite_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) error) *MockFavoriteServiceInterface_ToggleFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFavoriteServiceInterface creates a new instance of MockFavoriteServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteServiceInterface {
	mock := &MockFavoriteServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
