// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "savvy/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMerchantRepository is an autogenerated mock type for the MerchantRepository type
type MockMerchantRepository struct {
	mock.Mock
}

type MockMerchantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchantRepository) EXPECT() *MockMerchantRepository_Expecter {
	return &MockMerchantRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx
func (_m *MockMerchantRepository) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockMerchantRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMerchantRepository_Expecter) Count(ctx interface{}) *MockMerchantRepository_Count_Call {
	return &MockMerchantRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockMerchantRepository_Count_Call) Run(run func(ctx context.Context)) *MockMerchantRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMerchantRepository_Count_Call) Return(_a0 int64, _a1 error) *MockMerchantRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantRepository_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockMerchantRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, merchant
func (_m *MockMerchantRepository) Create(ctx context.Context, merchant *models.Merchant) error {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Merchant) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMerchantRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - merchant *models.Merchant
func (_e *MockMerchantRepository_Expecter) Create(ctx interface{}, merchant interface{}) *MockMerchantRepository_Create_Call {
	return &MockMerchantRepository_Create_Call{Call: _e.mock.On("Create", ctx, merchant)}
}

func (_c *MockMerchantRepository_Create_Call) Run(run func(ctx context.Context, merchant *models.Merchant)) *MockMerchantRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Merchant))
	})
	return _c
}

func (_c *MockMerchantRepository_Create_Call) Return(_a0 error) *MockMerchantRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Merchant) error) *MockMerchantRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMerchantRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMerchantRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMerchantRepository_Delete_Call {
	return &MockMerchantRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMerchantRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMerchantRepository_Delete_Call) Return(_a0 error) *MockMerchantRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockMerchantRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockMerchantRepository) GetAll(ctx context.Context) ([]models.Merchant, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Merchant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Merchant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMerchantRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMerchantRepository_Expecter) GetAll(ctx interface{}) *MockMerchantRepository_GetAll_Call {
	return &MockMerchantRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockMerchantRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockMerchantRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMerchantRepository_GetAll_Call) Return(_a0 []models.Merchant, _a1 error) *MockMerchantRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]models.Merchant, error)) *MockMerchantRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMerchantRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Merchant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Merchant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Merchant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMerchantRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockMerchantRepository_GetByID_Call {
	return &MockMerchantRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMerchantRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMerchantRepository_GetByID_Call) Return(_a0 *models.Merchant, _a1 error) *MockMerchantRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Merchant, error)) *MockMerchantRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockMerchantRepository) GetByName(ctx context.Context, name string) (*models.Merchant, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Merchant, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Merchant); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockMerchantRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMerchantRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockMerchantRepository_GetByName_Call {
	return &MockMerchantRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockMerchantRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockMerchantRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMerchantRepository_GetByName_Call) Return(_a0 *models.Merchant, _a1 error) *MockMerchantRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*models.Merchant, error)) *MockMerchantRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query
func (_m *MockMerchantRepository) Search(ctx context.Context, query string) ([]models.Merchant, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []models.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Merchant, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Merchant); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockMerchantRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockMerchantRepository_Expecter) Search(ctx interface{}, query interface{}) *MockMerchantRepository_Search_Call {
	return &MockMerchantRepository_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockMerchantRepository_Search_Call) Run(run func(ctx context.Context, query string)) *MockMerchantRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMerchantRepository_Search_Call) Return(_a0 []models.Merchant, _a1 error) *MockMerchantRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantRepository_Search_Call) RunAndReturn(run func(context.Context, string) ([]models.Merchant, error)) *MockMerchantRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, merchant
func (_m *MockMerchantRepository) Update(ctx context.Context, merchant *models.Merchant) error {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Merchant) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMerchantRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - merchant *models.Merchant
func (_e *MockMerchantRepository_Expecter) Update(ctx interface{}, merchant interface{}) *MockMerchantRepository_Update_Call {
	return &MockMerchantRepository_Update_Call{Call: _e.mock.On("Update", ctx, merchant)}
}

func (_c *MockMerchantRepository_Update_Call) Run(run func(ctx context.Context, merchant *models.Merchant)) *MockMerchantRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Merchant))
	})
	return _c
}

func (_c *MockMerchantRepository_Update_Call) Return(_a0 error) *MockMerchantRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Merchant) error) *MockMerchantRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchantRepository creates a new instance of MockMerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantRepository {
	mock := &MockMerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
