//go:build production
// +build production

// Package assets contains embedded frontend assets
package assets

import (
	"embed"
	"io/fs"
)

// Embed SvelteKit build output (client/)
// This directory contains the static SPA files generated by `npm run build`
// Only embedded in production builds
//
//go:embed all:client
var frontendFS embed.FS

// GetFrontendFS returns the embedded frontend filesystem
func GetFrontendFS() (fs.FS, error) {
	return fs.Sub(frontendFS, "client")
}
