---
# GoReleaser configuration for Savvy
# Only build Linux binaries (amd64 + arm64) for server deployment

version: 2

before:
  hooks:
    - go mod tidy
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate

builds:
  - id: savvy
    main: ./cmd/server
    binary: savvy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: savvy
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - AGENTS.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: sbaerlocher
    name: savvy
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Savvy {{ .Tag }} ({{ .Date }})

    ### Installation

    **Docker (recommended):**
    ```bash
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}
    ```

    **Helm Chart:**
    ```bash
    helm install savvy oci://ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/charts/savvy --version {{ .Tag }}
    ```

    **Binary (Linux amd64):**
    ```bash
    wget https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/savvy_{{ .Tag }}_linux_amd64.tar.gz
    tar xzf savvy_{{ .Tag }}_linux_amd64.tar.gz
    ./savvy
    ```

  footer: |
    ---
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    🤖 Built with [GoReleaser](https://goreleaser.com/)

# Announce to various channels (optional - disable for now)
announce:
  skip: true
