---
version: 2

before:
  hooks:
    # Go dependencies (download only, no tidy to preserve templ dependency)
    - go mod download

    # Frontend build (JS bundle)
    - npm ci --quiet
    - npm run build

    # Service Worker generation (inject version with cat instead of redirect)
    - bash -c "sed 's/__VERSION__/{{.Version}}/g' internal/assets/static/service-worker.js.tmpl > internal/assets/static/service-worker.js"

    # Verify service worker was created (optional - don't fail build)
    - bash -c "ls -lh internal/assets/static/service-worker.js || echo 'Warning: service-worker.js not found'"
    - bash -c "head -n 1 internal/assets/static/service-worker.js || echo 'Warning: cannot read service-worker.js'"

    # Template generation (generates *_templ.go files which import github.com/a-h/templ)
    - templ generate

    # Verify dependencies after code generation (optional)
    - go mod tidy

builds:
  - main: ./cmd/server
    binary: savvy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -extldflags "-static"
    flags:
      - -trimpath

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - .env.example

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: sbaerlocher
    name: savvy
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## 🎁 Savvy {{.Tag}}

    Savvy is a digital savvy card, voucher and gift card management system.

    ### 📦 Installation

    **Binary Downloads:**
    Choose the appropriate binary for your platform from the assets below.

    **Docker (Multi-Platform):**
    ```bash
    # Latest release (supports linux/amd64, linux/arm64)
    docker pull ghcr.io/sbaerlocher/container/savvy:{{.Tag}}
    ```

    **Docker Compose:**
    ```bash
    wget https://raw.githubusercontent.com/sbaerlocher/savvy/{{.Tag}}/docker-compose.yml
    wget https://raw.githubusercontent.com/sbaerlocher/savvy/{{.Tag}}/.env.example -O .env
    # Edit .env with your configuration
    docker compose up -d
    ```

    ### 🐳 Container Images
    - **Registry**: ghcr.io/sbaerlocher/container/savvy:{{.Tag}}
    - **Platforms**: linux/amd64, linux/arm64
    - **Tags**: `{{.Tag}}`, `{{.Major}}`, `{{.Major}}.{{.Minor}}`, `latest`

  footer: |
    **Full Changelog**: https://github.com/sbaerlocher/savvy/compare/{{.PreviousTag}}...{{.Tag}}

    ### 🔐 Verification
    ```bash
    sha256sum -c checksums.txt
    ```
