# Makefile for Savvy
#
# Development Workflow (Docker-based):
# 1. make dev      # Start Docker development (alias for make up)
# 2. make logs     # View application logs
# 3. make down     # Stop containers
#
# Production:
# - Production images built via GitHub Actions (.github/workflows/release.yml)
# - Use 'make build' for local binary builds

APP_NAME := savvy
VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
BUILD_TIME := $(shell date -u '+%Y-%m-%d_%H:%M:%S')

# Container names (development)
APP_CONTAINER := savvy-api
DB_CONTAINER := savvy-postgres

# Helm configuration
HELM_RELEASE := savvy
HELM_CHART := deploy/helm/savvy

# Helper commands
DOCKER_MIGRATE := docker exec $(APP_CONTAINER) go run -mod=mod /app/cmd/migrate/main.go

# ==============================================================================
# HELP
# ==============================================================================

.PHONY: help
help:
	@echo "Savvy Build Commands:"
	@echo ""
	@echo "Core:"
	@echo "  build          Build binary and JS bundle"
	@echo "  test           Run all tests"
	@echo "  test-core      Run core tests (services + models)"
	@echo "  clean          Remove build artifacts"
	@echo ""
	@echo "Development:"
	@echo "  dev            Start Docker development environment (alias for up)"
	@echo "  up             Start Docker containers with hot reload"
	@echo "  down           Stop Docker containers"
	@echo "  restart        Restart Docker containers"
	@echo "  rebuild        Rebuild Docker containers"
	@echo "  logs           Show API logs"
	@echo "  logs-client    Show client logs"
	@echo "  logs-db        Show database logs"
	@echo "  logs-all       Show all logs"
	@echo "  logs-mailpit   Show Mailpit logs"
	@echo "  shell          Open shell in app container"
	@echo "  db-shell       Open PostgreSQL shell"
	@echo "  mailpit        Open Mailpit web UI (http://localhost:8025)"
	@echo "  up-observability  Start observability stack (Grafana/Prometheus/Loki/Tempo)"
	@echo "  down-observability  Stop observability stack"
	@echo "  logs-observability  Show observability stack logs"
	@echo ""
	@echo "Database:"
	@echo "  migrate-up     Apply all pending migrations"
	@echo "  migrate-down   Rollback last migration"
	@echo "  migrate-reset  Rollback all migrations"
	@echo "  migrate-status Show applied migrations"
	@echo "  migrate-to     Migrate to specific version (TARGET_VERSION=...)"
	@echo "  seed           Seed database with test data"
	@echo ""
	@echo "Helm:"
	@echo "  helm-install   Install with Helm"
	@echo "  helm-upgrade   Upgrade with Helm"
	@echo "  helm-template  Preview Helm templates"
	@echo "  helm-lint      Lint Helm chart"
	@echo ""
	@echo "Kustomize:"
	@echo "  kustomize-dev        Deploy development"
	@echo "  kustomize-staging    Deploy staging"
	@echo "  kustomize-prod       Deploy production"
	@echo "  kustomize-preview-*  Preview manifests"
	@echo ""
	@echo "Quality:"
	@echo "  lint           Run golangci-lint"
	@echo "  fmt            Format Go code"
	@echo "  deps           Update dependencies"

# ==============================================================================
# CORE TARGETS
# ==============================================================================

.PHONY: build
build:
	@echo "🔨 Building $(APP_NAME)..."
	@echo "📦 Building client (SvelteKit) using release-tool..."
	go run cmd/release-tool/main.go build-client
	@echo "🔧 Building Go binary with embedded client..."
	go build -tags production -ldflags="-s -w -X main.version=$(VERSION) -X main.buildTime=$(BUILD_TIME)" -o bin/server cmd/server/main.go
	@echo "✓ Build complete (version: $(VERSION))"

# Service worker is now generated by Vite/Workbox during frontend build
# No separate generation needed

.PHONY: test
test:
	@echo "🧪 Running all tests..."
	go test -mod=mod -v -p=1 ./...

.PHONY: test-core
test-core:
	@echo "🧪 Running core tests (services + models)..."
	go test -mod=mod -v -p=1 ./internal/services ./internal/models

.PHONY: test-coverage
test-coverage:
	@echo "📊 Running tests with coverage..."
	go test -mod=mod -p=1 -coverprofile=coverage.out -covermode=atomic ./internal/services ./internal/models
	go tool cover -html=coverage.out -o coverage.html
	@echo "✓ Coverage report generated: coverage.html"
	@echo ""
	@go tool cover -func=coverage.out | grep total

.PHONY: test-coverage-ci
test-coverage-ci:
	@echo "📊 Running tests with coverage (CI mode)..."
	go test -mod=mod -coverprofile=coverage.out -covermode=atomic ./internal/services ./internal/models
	@go tool cover -func=coverage.out | grep total

.PHONY: clean
clean:
	@echo "🧹 Cleaning up..."
	rm -rf bin/
	rm -rf client/build/
	rm -rf client/.svelte-kit/
	rm -rf internal/assets/client/
	@echo "✓ Cleanup complete"

.PHONY: clean-port
clean-port:
	@echo "🧹 Cleaning up development ports..."
	@lsof -ti:5173 | xargs kill -9 2>/dev/null || echo "No process found on port 5173 (Frontend)"
	@lsof -ti:8080 | xargs kill -9 2>/dev/null || echo "No process found on port 8080 (Backend)"
	@lsof -ti:5432 | xargs kill -9 2>/dev/null || echo "No process found on port 5432 (PostgreSQL)"
	@echo "✓ Ports cleaned: 5173 (Frontend), 8080 (Backend), 5432 (PostgreSQL)"

.PHONY: clean-all
clean-all: clean clean-port
	@echo "🧹 Full cleanup completed"

# ==============================================================================
# DEVELOPMENT
# ==============================================================================
# IMPORTANT: Development MUST run in Docker (Vite proxy requires Docker network)
# See AGENTS.md for details

.PHONY: dev
dev: up

.PHONY: up
up:
	@echo "🚀 Starting development containers with hot reload..."
	@echo "📝 Watching: Go (Air) + SvelteKit (Vite HMR)"
	@echo "🔄 Auto-rebuild on file changes"
	@echo ""
	@echo "🔍 Checking for active E2E containers..."
	@if docker ps -q -f name=savvy-app-e2e 2>/dev/null | grep -q .; then \
		echo "⚠️  E2E container detected - stopping to avoid port conflicts..."; \
		docker compose stop app-e2e; \
		docker compose rm -f app-e2e; \
		echo "✓ E2E container stopped"; \
	else \
		echo "✓ No E2E container running"; \
	fi
	@echo ""
	docker compose up -d
	@echo "✓ Containers started"
	@echo "  Frontend: http://localhost:5173 (Vite dev server)"
	@echo "  Backend:  http://localhost:8080 (Go API)"
	@echo "  Mailpit:  http://localhost:8025 (Mail catcher)"
	@echo ""
	@echo "💡 View logs: make logs (API) | make logs-client (Frontend)"

.PHONY: up-observability
up-observability:
	@echo "📊 Starting Observability Stack..."
	docker compose --profile observability up -d
	@echo "✓ Observability stack started"
	@echo "  Grafana:    http://localhost:3000 (admin/admin)"
	@echo "  Prometheus: http://localhost:9090"
	@echo "  Loki:       http://localhost:3100"
	@echo "  Tempo:      http://localhost:3200"
	@echo ""
	@echo "💡 View logs: make logs-observability"

.PHONY: down
down:
	@echo "⏹️  Stopping containers..."
	docker compose down
	@echo "✓ Containers stopped"

.PHONY: down-observability
down-observability:
	@echo "⏹️  Stopping observability stack..."
	docker compose --profile observability down
	@echo "✓ Observability stack stopped"

.PHONY: restart
restart: down up

.PHONY: rebuild
rebuild:
	@echo "🔄 Rebuilding development containers..."
	docker compose down
	docker compose build --no-cache
	docker compose up -d
	@echo "✓ Rebuild complete"
	@echo "💡 View logs: make logs"

.PHONY: logs
logs:
	docker compose logs -f api

.PHONY: logs-client
logs-client:
	docker compose logs -f client

.PHONY: logs-db
logs-db:
	docker compose logs -f postgres

.PHONY: logs-all
logs-all:
	docker compose logs -f

.PHONY: logs-mailpit
logs-mailpit:
	docker compose logs -f mailpit

.PHONY: mailpit
mailpit:
	@echo "Opening Mailpit at http://localhost:8025"
	open http://localhost:8025

.PHONY: logs-observability
logs-observability:
	docker compose --profile observability logs -f

.PHONY: shell
shell:
	docker exec -it $(APP_CONTAINER) sh

.PHONY: db-shell
db-shell:
	docker exec -it $(DB_CONTAINER) psql -U savvy -d savvy

.PHONY: ps
ps:
	docker compose ps

# ==============================================================================
# DATABASE MIGRATIONS
# ==============================================================================
# IMPORTANT: Migrations run in Docker container (consistent with development environment)

.PHONY: migrate-up
migrate-up:
	@echo "🚀 Running migrations in Docker..."
	$(DOCKER_MIGRATE) up

.PHONY: migrate-down
migrate-down:
	@echo "⏪ Rolling back last migration in Docker..."
	$(DOCKER_MIGRATE) down

.PHONY: migrate-reset
migrate-reset:
	@echo "⚠️  Rolling back all migrations in Docker..."
	$(DOCKER_MIGRATE) reset

.PHONY: migrate-status
migrate-status:
	@echo "📋 Checking migration status in Docker..."
	$(DOCKER_MIGRATE) status

.PHONY: migrate-to
migrate-to:
	@if [ -z "$(TARGET_VERSION)" ]; then \
		echo "❌ Error: TARGET_VERSION parameter required"; \
		echo "Usage: make migrate-to TARGET_VERSION=202601230001_init_schema"; \
		exit 1; \
	fi
	@echo "🎯 Migrating to version $(TARGET_VERSION) in Docker..."
	$(DOCKER_MIGRATE) to $(TARGET_VERSION)

.PHONY: seed
seed:
	@echo "🌱 Seeding database in Docker..."
	docker exec $(APP_CONTAINER) go run -mod=mod /app/cmd/seed/main.go

# ==============================================================================
# HELM
# ==============================================================================

.PHONY: helm-install
helm-install:
	@echo "📦 Installing Helm chart..."
	helm install $(HELM_RELEASE) $(HELM_CHART)

.PHONY: helm-upgrade
helm-upgrade:
	@echo "🔄 Upgrading Helm release..."
	helm upgrade $(HELM_RELEASE) $(HELM_CHART)

.PHONY: helm-uninstall
helm-uninstall:
	@echo "🗑️  Uninstalling Helm release..."
	helm uninstall $(HELM_RELEASE)

.PHONY: helm-template
helm-template:
	@echo "🔍 Rendering Helm templates..."
	helm template $(HELM_RELEASE) $(HELM_CHART)

.PHONY: helm-lint
helm-lint:
	@echo "🔍 Linting Helm chart..."
	helm lint $(HELM_CHART)

# ==============================================================================
# KUSTOMIZE
# ==============================================================================

.PHONY: kustomize-dev
kustomize-dev:
	@echo "🚀 Deploying to development..."
	kubectl apply -k deploy/kustomize/overlays/development

.PHONY: kustomize-staging
kustomize-staging:
	@echo "🚀 Deploying to staging..."
	kubectl apply -k deploy/kustomize/overlays/staging

.PHONY: kustomize-prod
kustomize-prod:
	@echo "🚀 Deploying to production..."
	kubectl apply -k deploy/kustomize/overlays/production

.PHONY: kustomize-preview-dev
kustomize-preview-dev:
	@echo "🔍 Previewing development manifests..."
	kubectl kustomize deploy/kustomize/overlays/development

.PHONY: kustomize-preview-staging
kustomize-preview-staging:
	@echo "🔍 Previewing staging manifests..."
	kubectl kustomize deploy/kustomize/overlays/staging

.PHONY: kustomize-preview-prod
kustomize-preview-prod:
	@echo "🔍 Previewing production manifests..."
	kubectl kustomize deploy/kustomize/overlays/production

# ==============================================================================
# QUALITY & MAINTENANCE
# ==============================================================================

.PHONY: lint
lint:
	@echo "🔍 Running golangci-lint..."
	golangci-lint run

.PHONY: fmt
fmt:
	@echo "✨ Formatting Go code..."
	go fmt ./...

.PHONY: deps
deps:
	@echo "📦 Updating dependencies..."
	go mod tidy && go mod download
