---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-session
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-session
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: savvy-session-secret
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-db
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: savvy-db-password
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-smtp
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-smtp
    creationPolicy: Owner
  data:
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: savvy-smtp-credentials
        property: username
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: savvy-smtp-credentials
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-vapid
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-vapid
    creationPolicy: Owner
  data:
    - secretKey: VAPID_PRIVATE_KEY
      remoteRef:
        key: savvy-vapid-key
        property: privateKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-totp
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-totp
    creationPolicy: Owner
  data:
    - secretKey: TOTP_ENCRYPTION_KEY
      remoteRef:
        key: savvy-totp-encryption-key
        property: key
